import { arabicRecipeTitles } from "./catalog-foreign-titles";
type Locale = "ar" | "en" | "ja";
// Display translations never change the source identifier or the stored recipe.
// Use this only for catalog names and enums, never for a member's own prose.
const names: Record<string, string> = {
  "French Press": "فرنش برس",
  "Cold Brew": "كولد برو",
  "Pour Over": "ترشيح يدوي",
  "Single Origin": "أحادي المنشأ",
  "Black Honey": "عسلي أسود",
  "Double Anaerobic": "لاهوائي مزدوج",
  "Wet Hulled": "تقشير رطب",
  "Thermal Shock": "صدمة حرارية",
  "xBloom Official": "xBloom الرسمي",
  "Jeed roastery": "محمصة جيد",
  "Onyx Coffee Lab": "مختبر أونيكس للقهوة",
  "Workshop Coffee": "وركشوب كوفي",
  "Verve's Coffee Department": "قسم القهوة في فيرف",
  "Toby's Estate": "توبيز إيستيت",
  "ONA Coffee": "أونا كوفي",
  "NOMAD Coffee": "نوماد كوفي",
  "Methods Roastery": "محمصة ميثودز",
  "April Coffee Roasters": "محمصة أبريل",
  "Quarter Horse Coffee": "كوارتر هورس كوفي",
  "Five Senses Coffee": "فايف سينسز كوفي",
  "Rubens Gardelli": "روبينز غارديلي",
  "Roots Roastery": "محمصة روتس",
  "Coffee Collective": "كوفي كولكتيف",
  "Stumptown Coffee Roasters": "محمصة ستامبتاون",
  "Origin Coffee Roasters": "محمصة أوريجن",
  "Carmo de Minas": "كارمو دي ميناس",
  "Central America & Africa": "أمريكا الوسطى وأفريقيا",
  "East Africa": "شرق أفريقيا",
  "Papua New Guinea": "بابوا غينيا الجديدة",
  "Costa Rica": "كوستاريكا",
  "El Salvador": "السلفادور",
  "Saudi Arabia": "السعودية",
  "United States": "الولايات المتحدة",
  "United Kingdom": "المملكة المتحدة",
  "New Zealand": "نيوزيلندا",
  "South Korea": "كوريا الجنوبية",
  Bolivia: "بوليفيا",
  Brazil: "البرازيل",
  Colombia: "كولومبيا",
  Ecuador: "الإكوادور",
  Ethiopia: "إثيوبيا",
  Guatemala: "غواتيمالا",
  Honduras: "هندوراس",
  India: "الهند",
  Indonesia: "إندونيسيا",
  Kenya: "كينيا",
  Mexico: "المكسيك",
  Panama: "بنما",
  Peru: "بيرو",
  Rwanda: "رواندا",
  Tanzania: "تنزانيا",
  Uganda: "أوغندا",
  Yemen: "اليمن",
  China: "الصين",
  Thailand: "تايلند",
  Germany: "ألمانيا",
  Netherlands: "هولندا",
  Denmark: "الدنمارك",
  France: "فرنسا",
  Spain: "إسبانيا",
  Sweden: "السويد",
  Japan: "اليابان",
  Australia: "أستراليا",
  Singapore: "سنغافورة",
  Canada: "كندا",
  Italy: "إيطاليا",
  Kuwait: "الكويت",
  Qatar: "قطر",
  Bahrain: "البحرين",
  Oman: "عُمان",
  UAE: "الإمارات",
  "Hong Kong": "هونغ كونغ",
  Taiwan: "تايوان",
};
const words: Record<string, string> = {
  ice: "مثلّج",
  iced: "مثلّج",
  hot: "حار",
  cold: "بارد",
  natural: "طبيعي",
  washed: "مغسول",
  honey: "عسلي",
  anaerobic: "لاهوائي",
  blend: "خلطة",
  decaf: "منزوع الكافيين",
  coffee: "قهوة",
  roastery: "محمصة",
  roasters: "محمصة",
  roaster: "محمصة",
  official: "رسمي",
  recipe: "وصفة",
  filter: "ترشيح",
  espresso: "إسبريسو",
  classic: "كلاسيك",
  original: "الأصلي",
  studio: "ستوديو",
  pro: "برو",
  plus: "بلس",
  gen: "الجيل",
  cup: "كوب",
  cups: "أكواب",
  bomb: "بومب",
  bombe: "بومب",
  jeed: "جيد",
  single: "مفرد",
  origin: "منشأ",
  chocolate: "شوكولاتة",
  milk: "حليب",
  milky: "حليبي",
  cake: "كيك",
  watermelon: "بطيخ",
  whisky: "ويسكي",
  washedwet: "مغسول",
  process: "معالجة",
  geisha: "غيشا",
  gesha: "غيشا",
  holiday: "العطلات",
  house: "المنزل",
  fruity: "فاكهي",
  light: "فاتح",
  medium: "متوسط",
  dark: "داكن",
  roast: "تحميص",
  extended: "ممتد",
  fermented: "مخمّر",
  arabica: "أرابيكا",
  robusta: "روبوستا",
  heirloom: "سلالات محلية",
  bourbon: "بوربون",
  yellow: "أصفر",
  red: "أحمر",
  black: "أسود",
  white: "أبيض",
  blue: "أزرق",
  green: "أخضر",
  greenland: "غرينلاند",
  wet: "رطب",
  fermentednatural: "طبيعي مخمّر",
  omni: "متعدد الاستخدام",
  pour: "صب",
  over: "ترشيح",
  press: "كبس",
  brew: "تحضير",
  brewing: "تحضير",
  arabian: "عربي",
  ethiopian: "إثيوبي",
  colombian: "كولومبي",
  brazilian: "برازيلي",
  comandante: "كوماندانتي",
  fellow: "فيلو",
  timemore: "تايم مور",
  breville: "بريفيل",
  baratza: "باراتزا",
  acaia: "أكايا",
  niche: "نيش",
  kinu: "كينو",
  gaggia: "غاجيا",
  lelit: "ليليت",
  rancilio: "رانشيليو",
  hario: "هاريو",
  bialetti: "بياليتي",
  wacaco: "واكاكو",
  aeroPress: "إيروبريس",
  aeropress: "إيروبريس",
  chemex: "كيمكس",
  kalita: "كاليتا",
  origami: "أوريغامي",
  orea: "أوريا",
  cafec: "كافيك",
  normcore: "نورمكور",
  ecuador: "الإكوادور",
  ethiopia: "إثيوبيا",
  brazil: "البرازيل",
  colombia: "كولومبيا",
  panama: "بنما",
  kenya: "كينيا",
  yemen: "اليمن",
  guatemala: "غواتيمالا",
  peru: "بيرو",
  rwanda: "رواندا",
  uganda: "أوغندا",
  india: "الهند",
  china: "الصين",
  thailand: "تايلند",
  indonesia: "إندونيسيا",
  mexico: "المكسيك",
  default: "الافتراضي",
  new: "جديد",
  double: "مزدوج",
  lot: "محصول",
  finca: "فينكا",
  bloom: "التزهير",
  people: "بيبل",
  possession: "بوسيشن",
  sidra: "سيدرا",
  standout: "ستاند آوت",
  pink: "وردي",
  paperswan: "بيبر سوان",
  caturra: "كاتورا",
  catuai: "كاتواي",
  santa: "سانتا",
  future: "فيوتشر",
  aricha: "أريشا",
  lychee: "ليتشي",
  strawberry: "فراولة",
  brian: "براين",
  burundi: "بوروندي",
  peach: "خوخ",
  ombligon: "أومبليغون",
  standard: "قياسي",
  passion: "باشن",
  savage: "سافج",
  poma: "بوما",
  chiroso: "تشيروزو",
  fazenda: "فازيندا",
  lasso: "لاسو",
  juan: "خوان",
  fermentation: "تخمير",
  ferment: "تخمير",
  gotiti: "غوتيتي",
  chelchele: "تشيلتشيلي",
  hacienda: "هاسييندا",
  onyx: "أونيكس",
  fruit: "فاكهة",
  school: "سكول",
  pepe: "بيبي",
  andes: "أنديز",
  kebele: "كيبيلي",
  blending: "خلط",
  thermal: "حراري",
  shock: "صدمة",
  wave: "ويف",
  fully: "كامل",
  day: "يوم",
  rainbow: "قوس قزح",
  injerto: "إنخيرتو",
  eighty: "إيتي",
  paraiso: "بارايسو",
  bermudez: "بيرموديز",
  java: "جافا",
  perlitas: "بيرليتاس",
  cherry: "كرز",
  triangulo: "تريانغولو",
  rodrigo: "رودريغو",
  sanchez: "سانشيز",
  zero: "زيرو",
  wild: "وايلد",
  arriyadh: "الرياض",
  mixed: "مشكّل",
  test: "تجربة",
  of: "من",
  by: "لدى",
  no: "رقم",
  not: "غير",
  the: "الـ",
  and: "و",
  with: "مع",
  to: "إلى",
  for: "لـ",
  diego: "دييغو",
  parra: "بارا",
  wilder: "وايلدر",
  lazo: "لازو",
  bella: "بيلا",
  alex: "أليكس",
  aponte: "أبونتي",
  proud: "براود",
  mary: "ماري",
  rhys: "ريس",
  sean: "شون",
  chad: "تشاد",
  steven: "ستيفن",
  lin: "لين",
  french: "فرنسي",
  mattari: "مطري",
  guji: "غوجي",
  sidama: "سيداما",
  sidamo: "سيدامو",
};
/** Search aliases describe spellings/translations, never additional coffee facts. */
export const catalogSearchVocabulary: readonly (readonly string[])[] = [
  ...Object.entries(names),
  ...Object.entries(words).filter(([name]) => name.length >= 3),
];
const pairs: Record<string, string> = {
  sh: "ش",
  ch: "تش",
  th: "ث",
  ph: "ف",
  kh: "خ",
  gh: "غ",
  ee: "ي",
  oo: "و",
  ou: "و",
  ai: "اي",
  ay: "اي",
  ea: "ي",
  ie: "ي",
  ck: "ك",
  qu: "كو",
  ng: "نغ",
};
const letters: Record<string, string> = {
  a: "ا",
  b: "ب",
  c: "ك",
  d: "د",
  e: "ي",
  f: "ف",
  g: "غ",
  h: "ه",
  i: "ي",
  j: "ج",
  k: "ك",
  l: "ل",
  m: "م",
  n: "ن",
  o: "و",
  p: "ب",
  q: "ق",
  r: "ر",
  s: "س",
  t: "ت",
  u: "و",
  v: "ف",
  w: "و",
  x: "كس",
  y: "ي",
  z: "ز",
};
// Compile Unicode name matchers once, rather than hundreds of times per screen.
const nameMatchers = Object.entries(names)
  .sort((a, b) => b[0].length - a[0].length)
  .map(([name, translated]) => ({
    pattern: new RegExp(
      "(^|[^\\p{L}\\p{N}])" +
        name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") +
        "(?=$|[^\\p{L}\\p{N}])",
      "giu",
    ),
    translated,
  }));

export function catalogName(
  text: string | null | undefined,
  locale: Locale,
): string {
  if (!text || locale !== "ar") return text || "";
  if (arabicRecipeTitles[text]) return arabicRecipeTitles[text];
  if (names[text]) return names[text];
  let value = text;
  for (const { pattern, translated } of nameMatchers)
    value = value.replace(pattern, (_, prefix) => prefix + translated);
  return value.replace(/[A-Za-z][A-Za-zÀ-ž0-9'’.-]*/g, (token) => {
    if (
      /^(xBloom|V60|OREA|PID|USB|RPM|C40|J|K|SL|CMN|AA|AB|EA|MQ|CGLE|AG|PP|RFID|COE|AN|AW|W|F|BoC|M2M|C)$/i.test(
        token,
      ) ||
      /^[A-Z]{1,4}\d+[A-Za-z0-9.-]*$/.test(token)
    )
      return token;
    const lower = token.toLowerCase();
    if (words[lower]) return words[lower];
    if (lower === "g" || lower === "ml" || lower === "s") return token;
    // Phonetic catalog-name fallback. The exact spelling remains in source details.
    const latin = lower.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    return latin
      .replace(
        /sh|ch|th|ph|kh|gh|ee|oo|ou|ai|ay|ea|ie|ck|qu|ng|[a-z]/g,
        (part) => pairs[part] ?? letters[part] ?? part,
      )
      .replace(/[اأ]{2,}/g, "ا");
  });
}
