export const factLabels: Record<string, [string, string]> = {
  operation: ["التشغيل", "Operation"],
  focus: ["الاستخدام", "Designed for"],
  capacity: ["السعة المنشورة", "Published capacity"],
  coffee_capacity: ["كمية البن", "Coffee capacity"],
  burr_type: ["نوع التروس", "Burr type"],
  burr_diameter: ["قطر التروس", "Burr diameter"],
  burr: ["التروس", "Burrs"],
  burr_options: ["خيارات التروس", "Burr options"],
  adjustment: ["ضبط الطحنة", "Grind adjustment"],
  dosing: ["الجرعات", "Dosing"],
  grinder: ["الطاحونة المدمجة", "Integrated grinder"],
  heating: ["نظام التسخين", "Heating system"],
  boiler: ["الغلايات", "Boilers"],
  portafilter: ["البورتافلتر", "Portafilter"],
  steam: ["تبخير الحليب", "Milk steaming"],
  water_tank: ["خزان الماء", "Water tank"],
  brew_pressure: ["ضغط الاستخلاص", "Extraction pressure"],
  max_pump_pressure: ["الحد الأقصى للمضخة", "Maximum pump pressure"],
  pressure_gauge: ["مقياس الضغط", "Pressure gauge"],
  preinfusion: ["النقع الأولي", "Pre-infusion"],
  flow_control: ["التحكم بالتدفق", "Flow control"],
  heats_water: ["يسخّن الماء", "Heats water"],
  readability: ["دقة القراءة", "Readability"],
  timer: ["المؤقت", "Timer"],
  guidance: ["مساعدة التحضير", "Brew assistance"],
  display: ["الشاشة", "Display"],
  connection: ["الاتصال والشحن", "Connectivity and charging"],
  dimensions: ["الأبعاد", "Dimensions"],
  weight: ["الوزن", "Weight"],
  material: ["الخامة", "Material"],
  filter: ["الفلتر", "Filter"],
  compatibility: ["التوافق", "Compatibility"],
  spout: ["المصب", "Spout"],
  temperature: ["الحرارة", "Temperature"],
  hold: ["حفظ الحرارة", "Temperature hold"],
  motor_power: ["القدرة الكهربائية", "Electrical power"],
  voltage: ["الجهد", "Voltage"],
  drum_speed: ["سرعة الأسطوانة", "Drum speed"],
  battery: ["البطارية", "Battery"],
  made_in: ["الصناعة", "Made in"],
  included: ["المرفقات", "Included"],
  care: ["العناية", "Care"],
  sieves: ["شبكات المنخل", "Sieves"],
  springs: ["الزنبركات", "Springs"],
  sizes: ["المقاسات", "Sizes"],
  programs: ["البرامج", "Programs"],
  bottoms: ["قواعد التحضير", "Brewer bottoms"],
  own_beans: ["حبوبك الخاصة", "Your own beans"],
  handle: ["المقبض", "Handle"],
  use: ["الاستخدام", "Use"],
  region: ["إصدار السوق", "Market version"],
};
