export const additionalJapaneseLabels: Record<string, string> = {
  ' · Some data could not update': ' · 一部のデータを更新できませんでした', ' · Updating': ' · 更新中',
  '3–30 letters, numbers or underscores. Your username appears on your profile and in coffeeHO search.': '英字・数字・アンダースコアの3〜30文字。ユーザー名はプロフィールとcoffeeHOの検索に表示されます。',
  'A password reset link was sent to your email.': 'パスワード再設定のリンクをメールに送信しました。',
  'A verification code was sent to your email. Enter it to finish changing your password.': '確認コードをメールに送信しました。コードを入力してパスワードの変更を完了してください。',
  'Accept': '承認', 'Decline': '拒否', 'Account not found.': 'アカウントが見つかりません。', 'Account security': 'アカウントのセキュリティ',
  'Account deleted. Some device data could not be cleared; clear app data in your device settings.': 'アカウントを削除しました。一部の端末データを削除できませんでした。端末の設定からアプリのデータを消去してください。',
  'Account deletion was not confirmed. Check your connection and retry. Some uploaded files may already have been removed.': 'アカウントの削除を確認できませんでした。接続を確認して再試行してください。一部のファイルは削除済みの場合があります。',
  'Add equipment': '器具を追加', 'Add to My Bags': '在庫に追加', 'Added to My Bags. Complete its weight and dates in My Bags.': '在庫に追加しました。在庫の画面で重量と日付を入力してください。',
  'Altitude': '標高', 'Anaerobic': '嫌気性発酵', 'Bag weight': '袋の重量', 'Best setup': 'おすすめの設定', 'Brew methods': '抽出方法', 'Brew my coffee': '自分のコーヒーを淹れる', 'Brew photo': '抽出写真',
  'By continuing, you agree to the terms of use\nand privacy policy.': '続けることで、利用規約と\nプライバシーポリシーに同意したことになります。',
  'Cancel follow request': 'フォローリクエストを取り消す', 'Change email': 'メールアドレスを変更', 'Change password': 'パスワードを変更', 'Check confirmation': '確認状況を見る',
  'Choose JPEG, PNG or WebP under 5 MB.': '5 MB未満のJPEG・PNG・WebP画像を選んでください。',
  'Choose a password different from the current one.': '現在と異なるパスワードを選んでください。', 'Choose a recipe for your cup': '一杯のレシピを選ぶ',
  'Choose a stronger password with at least 8 characters.': '8文字以上の、より安全なパスワードを選んでください。', 'Choose photo': '写真を選択', 'Choose your brew method': '抽出方法を選ぶ',
  'Coffee & taste': 'コーヒーと風味', 'Coffee bags': 'コーヒー在庫', 'Coffee corner': 'コーヒーコーナー', 'Coffee origin photo': 'コーヒー産地の写真', 'Coffee photo source': '写真の情報元',
  'Coffee photo unavailable': 'コーヒーの写真がありません', 'Coffee picks': 'コーヒーのおすすめ', 'Coffee product photo': 'コーヒー商品の写真', 'Coffee shortcuts': 'コーヒーのメニュー', 'Coffees': 'コーヒー',
  'Community participation and messages are suspended after repeated violations.': '違反が繰り返されたため、コミュニティへの参加とメッセージを停止しています。',
  'Confirm account deletion': 'アカウント削除の確認', 'Confirm new password': '新しいパスワードの確認',
  'Confirmation is still pending. Check your current and new inboxes.': '確認はまだ完了していません。現在と新しいメールアドレスの受信箱を確認してください。',
  'Confirmation requested. Open the confirmation emails in your current and new inboxes if required. Your current email remains until verification is complete.': '確認メールを送信しました。必要に応じて現在と新しいメールの受信箱を確認してください。確認が完了するまでは現在のメールが有効です。',
  'Corner & brews': 'コーヒーコーナーと抽出', 'Could not add this coffee to My Bags.': 'このコーヒーを在庫に追加できませんでした。',
  'Could not confirm the action. Check your connection and retry.': '操作の完了を確認できませんでした。接続を確認して再試行してください。',
  'Could not confirm the change. Check your connection and retry.': '変更を確認できませんでした。接続を確認して再試行してください。',
  'Could not load notifications.': '通知を読み込めませんでした。', 'Could not load profile.': 'プロフィールを読み込めませんでした。',
  'Could not load the remaining recipes for this coffee.': 'このコーヒーの残りのレシピを読み込めませんでした。',
  'Could not save appearance. Choose it again to retry.': '表示設定を保存できませんでした。もう一度選んで再試行してください。', 'Could not update favorites. Try again.': 'お気に入りを更新できませんでした。再試行してください。',
  'Current password': '現在のパスワード', 'Deleting account…': 'アカウントを削除中…', 'Discover coffee origins': 'コーヒーの産地を探す', 'Email change awaiting confirmation': 'メール変更の確認待ち',
  'Enter a valid email different from your current one.': '現在と異なる、有効なメールアドレスを入力してください。', 'Enter the verification code sent to your email.': 'メールに届いた確認コードを入力してください。',
  'Explore ': '探す：', 'Explore now': '今すぐ探す', 'Explore your next cup': '次の一杯を探す', 'Farm': '農園', 'Favorites': 'お気に入り', 'Follow requests': 'フォローリクエスト',
  'From around the world': '世界各地から', 'From bean to cup, a better experience every day.': '豆から一杯まで、毎日もっと良いコーヒー体験を。', 'From espresso to cold brew': 'エスプレッソからコールドブリューまで', 'From my coffee bags': '自分のコーヒー在庫から',
  'General brewing guide': '基本の抽出ガイド', 'General starting recipe': '基本のレシピ', 'Honey': 'ハニープロセス', 'I have permission to share the photo': 'この写真を共有する権利を持っています',
  'If this email has an account, a password recovery message will arrive. Open its link on this device.': 'このメールにアカウントがある場合、再設定メールが届きます。この端末でリンクを開いてください。',
  'Last available data: ': '最後に取得したデータ：', 'Load more': 'さらに読み込む', 'Loading brew recipes…': '抽出レシピを読み込み中…', 'Loading profile…': 'プロフィールを読み込み中…',
  'Manage my bags': '在庫を管理', 'Manage my equipment': '器具を管理', 'Manage your sign-in email and password.': 'ログイン用のメールアドレスとパスワードを管理します。', 'More profile sections': 'その他のプロフィール項目', 'More recipes for this coffee': 'このコーヒーのレシピをさらに表示',
  'Name and username remain searchable. Private profile content is visible only to approved followers.': '名前とユーザー名は検索に表示されます。非公開プロフィールの内容は承認済みのフォロワーだけに表示されます。',
  'Natural': 'ナチュラルプロセス', 'New activity': '新しいアクティビティ', 'New email': '新しいメールアドレス', 'New password': '新しいパスワード',
  'No coffees match this brew method.': 'この抽出方法に合うコーヒーがありません。', 'No notifications right now.': '現在、通知はありません。', 'No results': '結果がありません', 'Open data source': '情報元を開く', 'Origins': '産地',
  'Password changed successfully.': 'パスワードを変更しました。', 'Password updated.': 'パスワードを更新しました。', 'Permanently delete my account': 'アカウントを完全に削除', 'Permanently delete your account?': 'アカウントを完全に削除しますか？',
  'Photo ': '写真 ', 'Photo caption': '写真の説明', 'Pick your coffee and start brewing': 'コーヒーを選んで抽出を始める', 'Profile photo saved.': 'プロフィール写真を保存しました。',
  'Recipes could not be loaded. Retry or explore the library.': 'レシピを読み込めませんでした。再試行するか、レシピ一覧を見てください。', 'Recommendations for your next cup': '次の一杯へのおすすめ',
  'Recommendations use a bounded recipe sample. Search the recipe library for the full catalog.': 'おすすめは一部のレシピから選んでいます。全体はレシピ一覧で検索できます。',
  'Reconnect': '再接続', 'Region': '地域', 'Retry photo': '写真を再読み込み', 'Retry profile': 'プロフィールを再読み込み', 'Roast date': '焙煎日', 'Roaster product artwork': 'ロースターの商品画像', 'Roaster website': 'ロースターのサイト', 'Roasteries': 'ロースター',
  'Save password': 'パスワードを保存', 'Save photo': '写真を保存', 'Save your favorite coffees with the heart button.': 'ハートのボタンでお気に入りのコーヒーを保存しましょう。', 'Save: ': '保存：', 'Saving this product is not available yet.': 'この商品の保存にはまだ対応していません。',
  'Search coffee, roaster or origin…': 'コーヒー・ロースター・産地を検索…', 'Search coffees, recipes and roasters': 'コーヒー・レシピ・ロースターを検索', 'Selected photo': '選択した写真', 'Selected recipe': '選択したレシピ',
  'Send confirmation link': '確認リンクを送信', 'Send password recovery link': 'パスワード再設定のリンクを送信', 'Share': '共有', 'Share equipment, coffee and favorites': '器具・コーヒー・お気に入りを共有',
  'Show equipment, coffee and favorites to people who can view my profile': 'プロフィールを閲覧できる人に器具・コーヒー・お気に入りを表示', 'Some data could not be loaded. Pull to refresh.': '一部のデータを読み込めませんでした。下に引いて更新してください。',
  'Start brewing with ': '抽出を始める：', 'Start with the coffee you have, then return to your best result.': '手元のコーヒーから始めて、お気に入りの結果をまた試しましょう。', 'The current password is incorrect.': '現在のパスワードが正しくありません。', 'The verification code is incorrect or expired.': '確認コードが正しくないか、有効期限が切れています。',
  'This account is private. Request to follow to view details after approval.': '非公開アカウントです。フォローをリクエストすると、承認後に詳細を閲覧できます。', 'This content is not available now.': 'このコンテンツは現在利用できません。', 'This email belongs to another account.': 'このメールアドレスは別のアカウントで使用されています。',
  'This removes your account and its associated data. It cannot be undone. Uploaded files may be removed before the process completes.': 'アカウントと関連データを削除します。この操作は取り消せません。処理の完了前にアップロード済みのファイルが削除される場合があります。',
  'Too many attempts. Wait a moment and try again.': '試行回数が多すぎます。少し待ってから再試行してください。', 'Tools and recommendations': '器具とおすすめ', 'Try again': '再試行', 'Type DELETE to confirm': '確認のため DELETE と入力してください', 'Unsave: ': '保存を解除：',
  'Use a name of at least 2 characters and a username of 3–30 lowercase letters, numbers or underscores.': '名前は2文字以上、ユーザー名は英小文字・数字・アンダースコアの3〜30文字にしてください。', 'Use at least 8 characters and matching passwords.': '8文字以上にして、確認用パスワードと一致させてください。',
  'Username is taken. Choose another.': 'このユーザー名は使用されています。別の名前を選んでください。', 'Variety: ': '品種：', 'Verification code': '確認コード', 'Verify ownership through the confirmation email. Sending a request does not change your sign-in email.': '確認メールから所有者であることを確認してください。リクエストの送信だけではログイン用メールは変更されません。', 'Verifying…': '確認中…', 'View all coffee': 'すべてのコーヒーを見る',
  'Warning: your story is off-topic. Repetition suspends participation and messages.': '警告：ストーリーがコーヒーのテーマから外れています。繰り返すと参加とメッセージが停止されます。', 'Washed': 'ウォッシュトプロセス',
  'You signed in with Google or Apple. Send a link to your email to set a password.': 'GoogleまたはAppleでログインしています。メールにリンクを送ってパスワードを設定できます。', 'Your account and its data were deleted.': 'アカウントとデータを削除しました。', 'Your coffee journey': 'コーヒーの旅', 'Your new email is confirmed.': '新しいメールアドレスを確認しました。', 'Your saved coffees and settings': '保存したコーヒーと設定',
};
