"""Build the reviewed bilingual catalog from saved manufacturer observations.
Usage: python curate.py /path/to/gear-sources /path/to/equipment-catalog.json
Facts belong to the named variant; missing facts remain absent. No prices or stock.
"""
import json, pathlib, sys
from urllib.parse import urljoin

root=pathlib.Path(__file__).parent
observations=json.load(open(pathlib.Path(sys.argv[1])/'observations.json'))
previous=json.load(open(sys.argv[2]))
sources={r['name']:r for r in observations}
old={r['name']:r for r in previous}
items=[]
def add(name,ar,category,description_ar,description_en,facts,methods=None,**extra):
    s=sources[name]
    if s.get('status')!=200: raise ValueError('Unverified source: '+name)
    items.append(dict(name=name,id=old.get(name,{}).get('id'),name_ar=ar,category=category,
      description_ar=description_ar,description_en=description_en,facts={k:list(v) for k,v in facts.items()},
      methods=methods if methods is not None else old.get(name,{}).get('suitable_brew_methods',[]),
      source={k:s.get(k) for k in ['url','final_url','title','checked_at','sha256','image_url']},**extra))
manual=('يدوي','Manual'); electric=('كهربائي','Electric'); conical=('مخروطي','Conical'); flat=('مسطح','Flat'); stepless=('متصل دون نقرات','Stepless')
add('1Zpresso J-Max','ون زبريسو J-Max','grinder','طاحونة يدوية بضبط خارجي ذي نقرات؛ بيانات الضبط موثقة في مقارنة الشركة مع J-Ultra.','Manual grinder with a clicked external adjustment, documented in the manufacturer’s J-Ultra comparison.',{'operation':manual,'adjustment':('8.8 ميكرون لكل نقرة','8.8 μm per click')},extra_sources=['https://1zpresso.coffee/j-ultra/'],image_verified=True)
add('Acaia Pearl','أكايا بيرل','scale','ميزان للتحضير مع عرض الوزن والوقت ومؤشر تدفق واتصال لاسلكي.','Brewing scale with weight, time, a flow-rate indicator and wireless connectivity.',{'capacity':('2000 غ','2000 g'),'readability':('0.1 غ','0.1 g'),'dimensions':('160 × 160 × 32 مم','160 × 160 × 32 mm'),'connection':('بلوتوث 5.0 · USB-C','Bluetooth 5.0 · USB-C')},image_verified=True)
add('Acaia Pearl Model S','أكايا بيرل S','scale','ميزان بدليل تحضير تفاعلي وتنبيهات صوتية. المواصفات تخص PS003 وPS004.','Scale with an interactive brew guide and sound notifications. Specifications refer to PS003 and PS004.',{'capacity':('3000 غ','3000 g'),'readability':('0.1 غ','0.1 g'),'dimensions':('160 × 160 × 32 مم','160 × 160 × 32 mm'),'connection':('بلوتوث 5.0 · USB-C','Bluetooth 5.0 · USB-C'),'guidance':('دليل تحضير وتنبيهات صوتية','Brew guide and sound notifications')},image_verified=True)
add('AeroPress Original','إيروبريس الأصلي','aeropress','أداة يدوية تجمع النقع والترشيح والضغط بالهواء. تحتاج إلى ماء ساخن منفصل.','Manual brewer combining immersion, filtration and air pressure; requires separately heated water.',{'operation':manual,'capacity':('10 أونصات سائلة · 1–2 كوب','10 fl oz · 1–2 cups'),'filter':('ورقي أو معدني متوافق','Compatible paper or metal filter')},image_verified=True)
add('Baratza Encore','باراتزا إنكور','grinder','طاحونة كهربائية موجهة لتحضير القهوة بالترشيح.','Electric grinder designed for filter brewing.',{'operation':electric,'focus':('الترشيح','Filter brewing')},image_verified=True)
add('Baratza Encore ESP','باراتزا إنكور ESP','grinder','طاحونة موجهة للإسبريسو مع ضبط من قمع الحبوب وكوب جرعات مرفق.','Espresso-focused grinder with hopper adjustment and an included dosing cup.',{'operation':electric,'focus':('الإسبريسو','Espresso'),'adjustment':('بتدوير قمع الحبوب','Turn of the hopper'),'included':('كوب جرعات','Dosing cup')},image_verified=True)
add('Baratza Sette 270','باراتزا سيتي 270','grinder','طاحونة إسبريسو بجرعات زمنية وضبط كبير وآخر دقيق متصل.','Espresso grinder with timed dosing, macro adjustment and stepless micro adjustment.',{'operation':electric,'focus':('الإسبريسو','Espresso'),'adjustment':('ضبط كبير ودقيق متصل','Macro and stepless micro'),'dosing':('زمني دون حمل البورتافلتر','Hands-free timed dosing')},image_verified=True)
add('Baratza Virtuoso+','باراتزا فيرتوسو بلس','grinder','طاحونة بتروس M2 ومؤقت قابل للضبط إلى عُشر الثانية.','Grinder with M2 burrs and a timer adjustable to a tenth of a second.',{'operation':electric,'burr':('M2','M2'),'timer':('تعديل بمقدار 0.1 ثانية','0.1-second adjustment')},image_verified=True)
add('Bialetti Moka Express','بياليتي موكا إكسبريس','other','موكا بوت من الألومنيوم للغاز والكهرباء؛ الحث يحتاج إلى صفيحة الشركة المتوافقة.','Aluminium moka pot for gas and electric hobs; induction requires the manufacturer’s compatible plate.',{'operation':('على الموقد','Stovetop'),'material':('ألومنيوم','Aluminium'),'compatibility':('غاز وكهرباء؛ صفيحة إضافية للحث','Gas and electric; separate induction plate'),'care':('شطف بالماء · غسل يدوي','Water rinse · hand wash')},image_verified=True)
add('Bonavita 1.0L Variable Temperature Kettle','بونافيتا غلاية متغيرة الحرارة 1 لتر','kettle','غلاية بمصب ضيق وضبط الحرارة وخاصية حفظ الحرارة لمدة تصل إلى ساعة.','Gooseneck kettle with temperature control and a hold function for up to an hour.',{'operation':electric,'capacity':('1 لتر','1 L'),'spout':('ضيق للصب المتحكم به','Gooseneck'),'temperature':('140–212°F كما في المصدر؛ حد °C المنشور غير متسق','140–212°F; published °C upper limit is inconsistent'),'hold':('حتى 60 دقيقة · 140–208°F','Up to 60 minutes · 140–208°F')},image_verified=True)
add('Breville Barista Express (BES870)','بريفيل باريستا إكسبريس BES870','espresso_machine','ماكينة إسبريسو بطاحونة مدمجة وتحكم حراري PID وتبخير حليب يدوي.','Espresso machine with an integrated grinder, PID temperature control and manual milk steaming.',{'operation':electric,'heating':('ملف حراري · PID','Thermocoil · PID'),'portafilter':('54 مم','54 mm'),'grinder':('مدمج · 16 إعدادًا','Integrated · 16 settings'),'steam':('يدوي','Manual'),'brew_pressure':('9 بار للاستخلاص','9 bar extraction')},image_verified=True)
add('Chemex Classic 6-Cup','كيمكس كلاسيك 6 أكواب','chemex','إبريق تحضير زجاجي للترشيح مع طوق خشبي وفلاتر كيمكس المناسبة.','Glass pour-over brewer with a wooden collar, used with compatible Chemex filters.',{'operation':manual,'capacity':('30 أونصة سائلة','30 fl oz'),'material':('زجاج بوروسيليكات','Borosilicate glass'),'filter':('فلاتر كيمكس للمقاس المناسب','Matching Chemex bonded filters')},image_verified=True)
add('Comandante C40 MK4','كوماندانتي C40 MK4','grinder','طاحونة يدوية بتروس نايترو بليد، مع وعاء زجاجي وآخر بوليمري للحبوب.','Manual Nitro Blade grinder supplied with a glass bean jar and a polymer bean jar.',{'operation':manual,'burr_type':conical,'burr':('نايترو بليد','Nitro Blade'),'capacity':('40 غ لكل وعاء','40 g per jar'),'made_in':('ألمانيا','Germany')},image_verified=True)
add('EG-1','ويبر EG-1','grinder','طاحونة جرعة واحدة بتروس مسطحة قابلة للتبديل؛ يختلف الاستخدام بحسب طقم التروس المختار.','Single-dose grinder with interchangeable flat burrs; brew suitability depends on the selected burr set.',{'operation':electric,'burr_type':flat,'burr_diameter':('80 مم','80 mm'),'adjustment':('نقرات 5 ميكرون','5 μm steps'),'weight':('13.5 كغ','13.5 kg'),'burr_options':('CORE للإسبريسو والترشيح؛ ULTRA للترشيح','CORE for espresso/filter; ULTRA for filter')},image_verified=True)
add('Feld47 Manual Coffee Grinder','نُوك فيلد 47','grinder','طاحونة يدوية بضبط متصل؛ يتوفر طقم تروس للإسبريسو أو للترشيح.','Stepless manual grinder offered with espresso or pour-over burr configurations.',{'operation':manual,'adjustment':stepless,'capacity':('42–50 غ','42–50 g'),'weight':('765 غ','765 g'),'dimensions':('195 × 54 مم','195 × 54 mm'),'burr_options':('إسبريسو أو ترشيح بحسب الاختيار','Espresso or pour-over, selected configuration')},image_verified=True)
add('Fellow Ode Gen 2','فيلو أود الجيل الثاني','grinder','طاحونة كهربائية للترشيح، لا لطحن الإسبريسو.','Electric filter-brewing grinder; not intended for espresso.',{'operation':electric,'focus':('الترشيح؛ غير مخصص للإسبريسو','Filter; not espresso'),'burr_type':flat,'burr_diameter':('64 مم','64 mm'),'adjustment':('31 نقرة','31 steps'),'capacity':('100 غ','100 g')},image_verified=True)
add('Fellow Opus 2 Conical Burr Grinder','فيلو أوبس 2','grinder','طاحونة للإسبريسو والترشيح بتروس مخروطية وضبط متصل وكوبين للجرعات.','Espresso and filter grinder with conical burrs, stepless adjustment and two catch cups.',{'operation':electric,'burr_type':conical,'burr_diameter':('48 مم','48 mm'),'adjustment':stepless,'compatibility':('كوب جرعات لبورتافلتر 54 و58 مم','Dosing cup for 54 and 58 mm portafilters')},image_verified=True)
add('Flair 58','فلير 58','espresso_machine','ماكينة إسبريسو بذراع يدوي ومقياس ضغط وتسخين مسبق كهربائي بثلاث درجات.','Manual lever espresso maker with a pressure gauge and three-level electric preheating.',{'operation':('ذراع يدوي مع تسخين كهربائي','Manual lever; electric preheat'),'portafilter':('58 مم','58 mm'),'heating':('تسخين مسبق بثلاث درجات','Three-level preheating'),'pressure_gauge':('مرفق','Included')},image_verified=True)
add('Gaggia Classic Pro (E24)','غاجيا كلاسيك برو E24','espresso_machine','ماكينة بغلاية نحاسية واحدة للإسبريسو والتبخير؛ بيانات المصدر تخص إصدار السوق الأمريكي.','Single brass-boiler espresso and steam machine; the source describes the North American version.',{'operation':electric,'boiler':('واحدة مزدوجة الاستخدام · نحاس','Single dual-use · brass'),'portafilter':('58 مم','58 mm'),'brew_pressure':('9 بار','9 bar'),'steam':('يدوي','Manual'),'region':('إصدار أمريكا الشمالية','North American version')},image_verified=True)
add('Hiroia Jimmy','هيرويا جيمي','scale','ميزان بشاشة لاسلكية قابلة للفصل وأوضاع للإسبريسو والترشيح.','Scale with a detachable wireless display and espresso/pour-over modes.',{'capacity':('2000 غ','2000 g'),'dimensions':('120 × 145 × 25 مم','120 × 145 × 25 mm'),'connection':('بلوتوث 4.1 · منفذ USB صغير','Bluetooth 4.1 · Micro-USB'),'display':('لاسلكية قابلة للفصل','Detachable wireless')},image_verified=True)
add('Kalita Wave 185','كاليتا ويف 185','kalita_dripper','قطّارة من عائلة ويف ذات قاعدة مسطحة، تستخدم فلاتر ويف المناسبة لمقاسها.','Flat-bottom Wave-family dripper, used with matching Wave filters.',{'operation':manual,'filter':('ويف 185','Wave 185')},image_verified=False,identity_only=True)
add('Kinu M47 Classic','كينو M47 كلاسيك','grinder','طاحونة يدوية معدنية بتروس مخروطية وضبط متصل وكوب مغناطيسي.','Metal manual grinder with conical burrs, stepless adjustment and a magnetic catch cup.',{'operation':manual,'burr_type':conical,'burr_diameter':('47 مم','47 mm'),'adjustment':stepless,'capacity':('40 غ','40 g'),'weight':('1175 غ','1175 g')},image_verified=True)
add('Kruve Sifter Plus','كروڤ سيفتر بلس','other','منخل للبن المطحون مع 15 شبكة بأحجام معلومة للمقارنة والضبط.','Ground-coffee sifter with 15 calibrated sieves for grind comparison and calibration.',{'operation':manual,'sieves':('15 شبكة · 200–1600 ميكرون','15 sieves · 200–1600 μm'),'capacity':('10–80 غ من البن المطحون','10–80 g grounds'),'care':('غسل يدوي؛ غير مناسب لغسالة الصحون','Hand wash; not dishwasher safe')},image_verified=True)
add('Linea Mini','لا مارزوكو لينيا ميني','espresso_machine','ماكينة إسبريسو بغلايتين وتحكم حراري PID؛ قد تختلف الملحقات بحسب الإصدار.','Dual-boiler espresso machine with PID temperature control; accessories vary by version.',{'operation':electric,'boiler':('غلايتان','Dual boiler'),'heating':('تحكم PID','PID control'),'steam':('عصا تبخير','Steam wand')},image_verified=True)
add('Nanopresso','واكاكو نانوبريسو','espresso_machine','أداة إسبريسو محمولة بمضخة يدوية؛ تحتاج إلى ماء ساخن منفصل.','Portable hand-pump espresso maker; requires separately heated water.',{'operation':manual,'capacity':('80 مل ماء','80 ml water'),'coffee_capacity':('8 غ؛ 16 غ مع طقم إضافي','8 g; 16 g with separate Barista Kit'),'max_pump_pressure':('حتى 18 بار؛ ليس هدفًا للاستخلاص','Up to 18 bar; not an extraction target'),'weight':('336 غ','336 g'),'heats_water':('لا','No')},image_verified=True)
add('Niche Zero','نيش زيرو','grinder','طاحونة كهربائية بجرعة واحدة وتروس مخروطية وضبط متصل.','Single-dose electric grinder with conical burrs and stepless adjustment.',{'operation':electric,'burr_type':conical,'burr_diameter':('63 مم','63 mm'),'adjustment':stepless,'weight':('4.1 كغ','4.1 kg'),'dimensions':('122 × 211 × 311 مم','122 × 211 × 311 mm')},image_verified=True)
add('Origami Dripper','أوريغامي قطّارة M','origami_dripper','قطّارة خزفية ذات طيات، متوافقة مع ورق مخروطي أو ورق ويف بالمقاس المناسب.','Ribbed porcelain dripper compatible with matching cone or Wave filter papers.',{'operation':manual,'material':('خزف','Porcelain'),'filter':('مخروطي أو ويف بالمقاس المناسب','Matching cone or Wave papers')},image_verified=True)
add('Silvia','رانشيليو سيلفيا','espresso_machine','ماكينة إسبريسو بغلاية واحدة وتنظيم حرارة بثرموستات وعصا تبخير يدوية.','Single-boiler espresso machine with thermostat temperature regulation and manual steaming.',{'operation':electric,'boiler':('واحدة · 0.3 لتر','Single · 0.3 L'),'heating':('ثرموستات','Thermostat'),'water_tank':('2 لتر','2 L'),'weight':('14 كغ','14 kg'),'steam':('يدوي','Manual')},image_verified=True)
add('Stagg EKG Electric Kettle','فيلو ستاغ EKG','kettle','غلاية كهربائية بمصب ضيق وضبط للحرارة. الشبكات والإعدادات المتقدمة تختلف في إصدارات برو.','Temperature-controlled electric gooseneck kettle; networking and advanced settings differ on Pro versions.',{'operation':electric,'capacity':('0.9 لتر','0.9 L'),'spout':('ضيق للترشيح','Gooseneck')},image_verified=True)
add('Timemore Chestnut C2','تايم مور تشستنَت C2','grinder','طاحونة يدوية من سلسلة تشستنَت. تفاصيل النسخة الأصلية تحتاج إلى دليل خاص بالموديل.','Chestnut-series manual grinder. Detailed original-model specifications require a model-specific manual.',{'operation':manual},image_verified=False,identity_only=True)
add('V60 Ceramic Dripper 02','هاريو V60 خزفي 02','v60_dripper','قطّارة خزفية مخروطية بمقاس 02 من هاريو.','Hario size-02 conical ceramic dripper.',{'operation':manual,'material':('خزف','Ceramic'),'capacity':('1–4 أكواب','1–4 cups'),'filter':('هاريو V60 مقاس 02','Hario V60 size 02')},image_verified=True)
add('xBloom Original','xBloom الأصلي','xbloom','ماكينة ترشيح آلية تدعم الحبوب الخاصة والقطّارة القابلة لإعادة الاستخدام وإدارة الوصفات في التطبيق الرسمي.','Automated pour-over machine supporting your own beans, a reusable dripper and recipes in the official app.',{'operation':('ترشيح آلي','Automated pour-over'),'own_beans':('مدعومة بقطّارة قابلة لإعادة الاستخدام','Supported with reusable dripper'),'connection':('تطبيق xBloom الرسمي','Official xBloom app')},image_verified=True)
add('xBloom Studio','xBloom ستوديو','xbloom','نظام ترشيح آلي مع أوضاع مستقلة للطاحونة والميزان والتحضير.','Automated pour-over system with independent grinder, scale and brewing modes.',{'operation':('آلي أو أوضاع مستقلة','Automated or independent modes'),'dimensions':('170 × 204 × 426 مم','170 × 204 × 426 mm'),'connection':('بلوتوث 5.0 · تطبيق xBloom','Bluetooth 5.0 · xBloom app'),'own_beans':('مدعومة','Supported')},image_verified=True)
add('TIMEMORE Sculptor 078S','تايم مور سكَلْبتَر 078S','grinder','طاحونة كهربائية بتروس مسطحة للإسبريسو والترشيح؛ تختلف عن تروس توربو في 078.','Flat-burr electric grinder for espresso and filter; distinct from the 078 Turbo burr model.',{'operation':electric,'burr_type':flat,'focus':('الإسبريسو والترشيح','Espresso and filter'),'motor_power':('400 واط · سلسلة 078','400 W · 078 series')},['espresso','v60','aeropress','chemex'],image_verified=True)
add('1Zpresso K-Ultra','ون زبريسو K-Ultra','grinder','طاحونة يدوية متعددة الاستخدام بتروس مخروطية سباعية وضبط خارجي.','All-purpose manual grinder with heptagonal conical burrs and external adjustment.',{'operation':manual,'burr_type':conical,'adjustment':('20 ميكرون لكل نقرة · 100 نقرة للدورة','20 μm per click · 100 clicks/rotation')},['espresso','v60','aeropress','chemex'],image_verified=True)
add('1Zpresso J-Ultra','ون زبريسو J-Ultra','grinder','طاحونة يدوية للإسبريسو بضبط دقيق ذي نقرات وكوب مغناطيسي.','Espresso-focused manual grinder with fine clicked adjustment and a magnetic catch cup.',{'operation':manual,'burr_type':conical,'burr_diameter':('48 مم','48 mm'),'adjustment':('8 ميكرون لكل نقرة','8 μm per click'),'capacity':('35–40 غ','35–40 g'),'weight':('670 غ','670 g')},['espresso'],image_verified=True)
add('Niche Duo','نيش ديو','grinder','طاحونة جرعة واحدة بتروس مسطحة؛ طقم الترشيح الثاني يتوقف على خيار الطلب.','Single-dose flat-burr grinder; the second filter burr set depends on the ordered option.',{'operation':electric,'burr_type':flat,'burr_diameter':('83 مم','83 mm'),'adjustment':stepless,'weight':('5 كغ','5 kg'),'dimensions':('135 × 230 × 355 مم','135 × 230 × 355 mm'),'burr_options':('إسبريسو؛ طقم ترشيح بحسب الاختيار','Espresso; optional filter burr set')},['espresso','v60','chemex','aeropress'],image_verified=True)
add('Breville Bambino Plus','بريفيل بامبينو بلس','espresso_machine','ماكينة مدمجة بتسخين سريع وتبخير حليب تلقائي مع ثلاثة إعدادات للحرارة والقوام.','Compact fast-heating machine with automatic milk steaming and three temperature/texture settings.',{'operation':electric,'heating':('ثيرموجِت · تسخين 3 ثوانٍ','ThermoJet · 3-second heat-up'),'portafilter':('54 مم','54 mm'),'steam':('تلقائي أو يدوي','Automatic or manual'),'grinder':('غير مدمج','Not integrated'),'brew_pressure':('9 بار','9 bar')},['espresso'],image_verified=True)
add('Breville Bambino','بريفيل بامبينو','espresso_machine','ماكينة إسبريسو مدمجة بتسخين سريع وعصا تبخير يدوية.','Compact espresso machine with fast heat-up and manual milk steaming.',{'operation':electric,'heating':('ثيرموجِت · تسخين 3 ثوانٍ','ThermoJet · 3-second heat-up'),'portafilter':('54 مم','54 mm'),'steam':('يدوي','Manual'),'grinder':('غير مدمج','Not integrated'),'brew_pressure':('9 بار','9 bar')},['espresso'],image_verified=True)
add('Breville Dual Boiler','بريفيل دوال بويلر','espresso_machine','ماكينة بغلاية إسبريسو وغلاية بخار مستقلتين وتحكم PID.','Machine with independent espresso and steam boilers and PID control.',{'operation':electric,'boiler':('غلايتان مستقلتان','Independent dual boilers'),'heating':('تحكم PID','PID control'),'portafilter':('58 مم','58 mm'),'steam':('يدوي','Manual'),'grinder':('غير مدمج','Not integrated')},['espresso'],image_verified=True)
add('Breville Barista Pro','بريفيل باريستا برو','espresso_machine','ماكينة إسبريسو بتسخين سريع وطاحونة مدمجة بـ30 إعدادًا وتبخير يدوي.','Fast-heating espresso machine with a 30-setting integrated grinder and manual steaming.',{'operation':electric,'heating':('ثيرموجِت · تسخين 3 ثوانٍ','ThermoJet · 3-second heat-up'),'portafilter':('54 مم','54 mm'),'grinder':('مدمج · 30 إعدادًا','Integrated · 30 settings'),'steam':('يدوي','Manual'),'brew_pressure':('9 بار','9 bar')},['espresso'],image_verified=True)
add('Rancilio Silvia Pro X','رانشيليو سيلفيا برو X','espresso_machine','ماكينة بغلايتين ومتحكمي PID ونقع أولي منخفض الضغط قابل للضبط.','Dual-boiler machine with two PID controllers and adjustable low-pressure soft infusion.',{'operation':electric,'boiler':('غلايتان','Dual boiler'),'heating':('متحكما PID','Two PID controllers'),'preinfusion':('0–6 ثوانٍ','0–6 seconds'),'steam':('يدوي','Manual'),'timer':('مؤقت الاستخلاص','Shot timer')},['espresso'],image_verified=True)
add('Wacaco Picopresso','واكاكو بيكوبريسو','espresso_machine','أداة إسبريسو محمولة بمضخة يدوية وسلة غير مضغوطة؛ لا تسخّن الماء.','Portable hand-pump espresso maker with an unpressurised basket; does not heat water.',{'operation':manual,'capacity':('80 مل ماء','80 ml water'),'coffee_capacity':('18 غ','18 g'),'max_pump_pressure':('حتى 18 بار','Up to 18 bar'),'brew_pressure':('9–12 بار في إرشادات الشركة','9–12 bar in manufacturer guidance'),'heats_water':('لا','No')},['espresso'],image_verified=True)
add('Acaia Lunar 2021','أكايا لونار 2021','scale','ميزان مدمج للإسبريسو. المواصفات تخص AL008 وAL009 وAL010 وAL012 وAL013.','Compact espresso scale; specifications refer to AL008/AL009/AL010/AL012/AL013.',{'capacity':('2000 غ','2000 g'),'readability':('0.1 أو 0.01 غ','0.1 or 0.01 g'),'dimensions':('105 × 105 × 15 مم','105 × 105 × 15 mm'),'connection':('بلوتوث 5.0 · USB-C','Bluetooth 5.0 · USB-C')},['espresso','v60'],image_verified=True)
add('Fellow Tally Pro','فيلو تالي برو','scale','ميزان وزن ووقت مع وضع مساعد يحسب هدف الماء من نسبة البن التي تختارها.','Weight/timer scale with Brew Assist to calculate a water target from your chosen coffee ratio.',{'capacity':('2500 غ','2500 g'),'readability':('0.1 غ','0.1 g'),'dimensions':('177 × 150 × 33 مم','177 × 150 × 33 mm'),'connection':('شحن USB-C','USB-C charging'),'guidance':('مساعد النسبة والوزن والوقت','Ratio assist, weight and time')},['v60','chemex','aeropress'],image_verified=True)
add('Fellow Corvo EKG Pro','فيلو كورفو EKG برو','kettle','غلاية بمصب عريض للماء الساخن مع ضبط الحرارة؛ ليست بمصب ستاغ الضيق.','Temperature-controlled wide-spout hot-water kettle, distinct from the Stagg gooseneck.',{'operation':electric,'capacity':('0.9 لتر','0.9 L'),'temperature':('40–100°C','40–100°C'),'spout':('عريض','Wide'),'dimensions':('222 × 172 × 196 مم','222 × 172 × 196 mm')},['french_press','aeropress'],image_verified=True)
add('Hario Switch 02','هاريو سويتش 02','v60_dripper','قطّارة تجمع النقع والترشيح بمفتاح يفتح خروج الماء؛ هذه بيانات مقاس 02.','Switch-operated immersion/pour-over brewer; these specifications refer to size 02.',{'operation':manual,'capacity':('200 مل للتحضير بالنقع','200 ml finished immersion capacity'),'filter':('V60 مقاس 02','V60 size 02'),'dimensions':('118 × 115 × 133 مم','118 × 115 × 133 mm')},['switch'],image_verified=True)
add('AeroPress Go','إيروبريس غو','aeropress','أداة تحضير للسفر مع كوب يتسع لتخزين القطع داخله.','Travel brewer supplied with a mug that stores the brewing parts.',{'operation':manual,'capacity':('8 أونصات سائلة · كوب واحد','8 fl oz · 1 cup'),'included':('كوب للسفر','Travel mug')},['aeropress'],image_verified=True)
add('AeroPress XL','إيروبريس XL','aeropress','إيروبريس بسعة أكبر مع إبريق تقديم وفلاتر XL الخاصة به.','Larger AeroPress supplied with a carafe and requiring XL-size filters.',{'operation':manual,'capacity':('20 أونصة سائلة · 2–4 أكواب','20 fl oz · 2–4 cups'),'filter':('فلاتر XL؛ تختلف عن المقاس الأصلي','XL filters; different from Original size'),'included':('إبريق تقديم','Carafe')},['aeropress'],image_verified=True)
add('Chemex Classic 3-Cup','كيمكس كلاسيك 3 أكواب','chemex','كيمكس صغير للترشيح مع طوق خشبي وفلاتر خاصة بالمقاس.','Small pour-over Chemex with a wooden collar and size-specific filters.',{'operation':manual,'capacity':('15 أونصة سائلة كما ورد في المصدر','15 fl oz as stated in source'),'material':('زجاج بوروسيليكات','Borosilicate glass'),'filter':('فلاتر كيمكس 3 أكواب','Chemex 3-cup filters')},['chemex'],image_verified=True)
add('CAFEC Abaca Filters','كافيك فلاتر أباكا','filter','ورق ترشيح ياباني مصنوع من ألياف الأباكا ولب الخشب؛ اختر الشكل والمقاس المناسبين للقطّارة.','Japanese filter paper made from abaca fibre and wood pulp; choose a brewer-compatible shape and size.',{'material':('ألياف أباكا ولب خشب','Abaca fibre and wood pulp'),'made_in':('اليابان','Japan'),'compatibility':('حسب شكل الفلتر ومقاسه','Depends on paper shape and size')},['v60'],image_verified=True)
add('Fellow Atmos 1.2L','فيلو أتموس اليدوي 1.2 لتر','other','وعاء حفظ يفرّغ الهواء بلف الغطاء. هذه بيانات سعة 1.2 لتر والغطاء اليدوي.','Twist-lid vacuum storage canister; refers to the 1.2 L size and manual lid.',{'operation':('تفريغ يدوي بلف الغطاء','Manual twist vacuum'),'capacity':('1.2 لتر','1.2 L'),'coffee_capacity':('حتى 16 أونصة للتحميص الفاتح والمتوسط؛ أقل للداكن','Up to 16 oz light/medium roast; less for dark'),'care':('غير مناسب لغسالة الصحون','Not dishwasher safe')},[],image_verified=False)
add('Fellow Prismo','فيلو بريزمو','other','صمام وفلتر معدني للإيروبريس الأصلي؛ التحضير الناتج بأسلوب الإسبريسو ولا يساوي ماكينة إسبريسو.','Valve and metal filter for AeroPress Original; makes espresso-style coffee rather than machine espresso.',{'operation':manual,'compatibility':('إيروبريس الأصلي؛ تحقّق من الإصدار قبل الشراء','AeroPress Original; check version before purchase'),'filter':('معدني قابل لإعادة الاستخدام · 150 ميكرون','Reusable metal · 150 μm')},['aeropress'],image_verified=True)
add('Normcore V4 Tamper','نورمكور مكبس V4','distribution_tool','مكبس مزوّد بزنبرك وقاعدة تسوية. اختر القطر المطابق لسلتك؛ المقاسات ليست متبادلة.','Spring-loaded, self-levelling tamper; select the diameter matching your basket.',{'operation':manual,'springs':('15 و25 و30 رطلًا','15, 25 and 30 lb'),'compatibility':('53.3 مم لسلال 54 مم؛ مقاسات أخرى منفصلة','53.3 mm for 54 mm baskets; other sizes separate'),'sizes':('58.5 و58 و57.5 و53.3 مم وغيرها','58.5, 58, 57.5, 53.3 mm and other sizes')},['espresso'],image_verified=True)
add('Weber Blind Shaker','ويبر بلايند شيكر','distribution_tool','كوب لإعادة توزيع البن المطحون قبل نقله إلى سلة الإسبريسو.','Ground-coffee redistribution cup for transferring grounds into an espresso basket.',{'operation':manual,'compatibility':('مصمم لسلال 58 مم','Designed for 58 mm baskets')},['espresso'],image_verified=True)
add('Subminimal NanoFoamer PRO GEN-2','سابمينيمال نانوفومر برو','other','جهاز لتسخين الحليب وتكوين رغوته مع برامج قابلة للاختيار؛ تسمية الإصدار غير محددة في صفحة المصدر.','Milk heating and microfoam device with selectable programs; the source page does not identify a generation.',{'operation':electric,'programs':('6 برامج','6 programs'),'temperature':('حتى 70°C ±3°C بحسب الشركة','Up to 70°C ±3°C per manufacturer')},['espresso'],catalog_name='Subminimal NanoFoamer PRO',image_verified=True)
add('LELIT Bianca','ليليت بيانكا PL162T','espresso_machine','ماكينة بغلايتين وتحكم في تدفق الماء، مع خزان يمكن نقله إلى ثلاثة جوانب.','Dual-boiler machine with water-flow control and a tank that can be placed on three sides.',{'operation':electric,'boiler':('قهوة 800 مل · بخار 1.5 لتر','Coffee 800 ml · steam 1.5 L'),'water_tank':('2.5 لتر','2.5 L'),'portafilter':('58 مم','58 mm'),'weight':('27.2 كغ','27.2 kg'),'flow_control':('ذراع للتحكم في التدفق','Flow-control paddle')},['espresso'],image_verified=True)
add('April Plastic Brewer','أبريل قطّارة بلاستيكية','other','قطّارة من مجموعة أبريل مصنوعة من راتنج AS؛ استخدم الفلتر الموصى به للموديل.','April brewer made from AS resin; use the filter recommended for the model.',{'operation':manual,'material':('راتنج AS','AS resin'),'filter':('ورق أبريل المناسب للموديل','Model-compatible April paper')},['april'],image_verified=False)
add('Melodrip','ميلودريب','other','أداة يدوية لتوزيع الماء أثناء الصب بمقبض من الفولاذ المصقول.','Manual pour-water distribution tool with a polished steel handle.',{'operation':manual,'use':('توزيع ماء الصب','Pour-water distribution'),'handle':('فولاذ مصقول','Polished steel')},['v60','chemex'],image_verified=True)
add('Aillio Bullet R2','أيليو بولِت R2','roaster','ماكينة تحميص أسطوانية بالتسخين الحثي، مع قياس حرارة بالأشعة ومسبار.','Induction-heated drum roaster with infrared temperature sensing and a bean probe.',{'operation':electric,'capacity':('150–1000 غ للدفعة','150–1000 g batch'),'motor_power':('1700 واط','1700 W'),'voltage':('110–120 أو 200–240 فولت؛ بحسب النسخة','110–120 or 200–240 V, version dependent'),'heating':('حثي · 10 درجات قدرة','Induction · 10 power steps'),'drum_speed':('9 درجات · 30–90 دورة/دقيقة','9 steps · 30–90 RPM'),'connection':('USB-C وتطبيق روست تايم','USB-C and RoasTime')},[],image_verified=True)
add('Aillio Bullet R2 Pro','أيليو بولِت R2 برو','roaster','إصدار برو بسعة وقدرة أعلى؛ يتطلب 200–240 فولت وفق مواصفات الشركة.','Higher-capacity/power Pro version, requiring 200–240 V per manufacturer specifications.',{'operation':electric,'capacity':('150–1200 غ للدفعة','150–1200 g batch'),'motor_power':('2300 واط','2300 W'),'voltage':('200–240 فولت فقط','200–240 V only'),'heating':('حثي · 14 درجة قدرة','Induction · 14 power steps'),'drum_speed':('9 درجات · 30–90 دورة/دقيقة','9 steps · 30–90 RPM'),'connection':('USB-C وتطبيق روست تايم','USB-C and RoasTime')},[],image_verified=False)
add('IKAWA Pro 100','إيكاوا برو 100','roaster','ماكينة عينات تحميص مع إدارة منحنى التحميص عبر التطبيق الرسمي.','Sample roaster with roast-profile management through the official app.',{'operation':electric,'capacity':('دفعة اسمية 100 غ؛ راجع حدود الدفعة في دليل الشركة','Nominal 100 g batch; see manufacturer batch limits'),'connection':('بلوتوث · تطبيق إيكاوا برو','Bluetooth · IKAWA Pro app')},[],image_verified=False,extra_sources=['https://www.ikawacoffee.com/professional-faq/'])
add('TIMEMORE Black Mirror Basic 2','تايم مور بلاك ميرور بيسك 2','scale','ميزان مع مؤقت تلقائي ووظيفة قياس تدفق الماء وبطارية قابلة للشحن.','Scale with an automatic timer, water-flow measurement and a rechargeable battery.',{'timer':('تلقائي','Automatic'),'guidance':('عرض تدفق الماء','Water-flow display'),'connection':('شحن USB','USB charging'),'battery':('1600 ملي أمبير·ساعة؛ حتى 10 ساعات وفق الشركة','1600 mAh; up to 10 hours per manufacturer')},['v60','espresso','chemex'],image_verified=True)
add('Hario V60 02 Paper Filters','هاريو فلاتر V60 02','filter','فلاتر ورقية مصممة لقطّارة V60 مقاس 02.','Paper filters designed for size-02 V60 drippers.',{'compatibility':('V60 مقاس 02','V60 size 02'),'capacity':('1–4 أكواب','1–4 cups'),'material':('ورق ترشيح','Filter paper')},['v60'],image_verified=True)
add('La Marzocco Linea Micra','لا مارزوكو لينيا ميكرا','espresso_machine','ماكينة مدمجة بغلايتين ومجموعة تحضير مدمجة وتحكم PID وتطبيق منزلي.','Compact machine with dual boilers, an integrated grouphead, PID control and home-app settings.',{'operation':electric,'boiler':('غلايتان','Dual boiler'),'heating':('تحكم PID','PID control'),'weight':('19 كغ','19 kg'),'connection':('تطبيق لا مارزوكو المنزلي','La Marzocco Home app')},['espresso'],image_verified=True)
add('OREA V4','OREA V4','other','قطّارة بوحدات قابلة للتبديل وأربع قواعد مختلفة؛ اختيار القاعدة والورق يغيّر أسلوب التحضير.','Modular brewer with four different bottoms; bottom and paper selection change the brewing setup.',{'operation':manual,'capacity':('حتى كوبين وفق الشركة','Up to two cups per manufacturer'),'bottoms':('4: سريعة وكلاسيكية ومفتوحة وأبيكس','4: Fast, Classic, Open and Apex'),'filter':('ويف أو مسطح أو سيباريست بحسب الإعداد','Wave, flat or Sibarist, setup dependent')},['orea'],image_verified=False)

for item in items:
    # No generic logo, homepage banner or wrong-generation product photo.
    if not item.pop('image_verified'): item['source']['image_url']=None
    if item['source']['image_url'] and item['source']['image_url'].startswith('http://'):item['source']['image_url']='https://'+item['source']['image_url'][7:]
    if item['source']['image_url'] and item['source']['image_url'].startswith('//'):item['source']['image_url']='https:'+item['source']['image_url']
    if item['source']['image_url']:item['source']['image_url']=urljoin(item['source']['final_url'] or item['source']['url'],item['source']['image_url'])
json.dump({'schema_version':1,'items':items},open(root/'catalog.json','w'),ensure_ascii=False,indent=2)
json.dump(previous,open(root/'before.json','w'),ensure_ascii=False,indent=2)
print(json.dumps({'models':len(items),'existing':sum(bool(i['id']) for i in items),'new':sum(not i['id'] for i in items),'facts':sum(len(i['facts']) for i in items)}))
