/** Display spellings of reviewed catalog coffee names, indexed in both languages. Updated 2026-10-09. */
export const coffeeNameAliases: readonly (readonly string[])[] = [
  ["3056 Espresso Blend", "3056 إسبريسو خلطة"],
  ["360° Profile Blend", "360° بروفيلي خلطة"],
  ["Agostinho Forest", "اغوستينهو فوريست"],
  ["Alba — 250 g", "البا — 250 g"],
  ["All Black Knight coffees — iced", "الل أسود كنيغت كوففيس — مثلّج"],
  [
    "AmberWood Reserve (Wood-Fired Coffee)",
    "امبيروود ريسيرفي (وود-فيريد قهوة)",
  ],
  [
    "AppleWood Reserve (Wood-Fired Coffee)",
    "اببليوود ريسيرفي (وود-فيريد قهوة)",
  ],
  ["Aquiares — Costa Rica — Natural", "اكوياريس — كوستاريكا — طبيعي"],
  ["Arabic Gahwa", "ارابيك غاهوا"],
  ["Ardi", "اردي"],
  ["Aspen", "اسبين"],
  ["Atlas Coffee", "اتلاس قهوة"],
  ["Bani Ismail | Yemen", "باني يسمايل | اليمن"],
  ["Barista Elite Supremo Espresso", "باريستا يليتي سوبريمو إسبريسو"],
  ["Benti Nenqa — Ethiopia — Washed", "بينتي نينقا — إثيوبيا — مغسول"],
  ["Berry Blues", "بيرري بلويس"],
  ["Big Trouble", "بيغ تروبلي"],
  ["Big Truck", "بيغ تروك"],
  ["Bittersweet", "بيتتيرسويت"],
  ["Black Cat Classic Espresso", "أسود كات كلاسيك إسبريسو"],
  ["Black Diamond", "أسود دياموند"],
  ["black forest blend", "أسود فوريست خلطة"],
  ["Black Forest Blend", "أسود فوريست خلطة"],
  ["Black Swan", "أسود سوان"],
  ["Blue Sky Espresso", "أزرق سكي إسبريسو"],
  [
    "Bolivia Gregorio Palli, Anoxic Washed",
    "بوليفيا غريغوريو باللي, انوكسيك مغسول",
  ],
  ["Bombe — Ethiopia — Natural", "بومب — إثيوبيا — طبيعي"],
  ["Bond Street Espresso Blend", "بوند ستريت إسبريسو خلطة"],
  ["Bossa Nova | Brazil", "بوسسا نوفا | البرازيل"],
  ["Brazil", "البرازيل"],
  ["Brazil — Classic", "البرازيل — كلاسيك"],
  ["Brazil Alta Mogiana", "البرازيل التا موغيانا"],
  ["Brazil Cascavel Vermelha (Natural)", "البرازيل كاسكافيل فيرميلها (طبيعي)"],
  ["Brazil Diamond", "البرازيل دياموند"],
  ["Brazil Fazenda Samambaia", "البرازيل فازيندا سامامبايا"],
  ["Brazil Inacio Urban", "البرازيل يناكيو وربان"],
  ["Brazil Rancho Grande Estate", "البرازيل رانتشو غراندي يستاتي"],
  ["Brazil Roast", "البرازيل تحميص"],
  ["Brazil Santa Lucia", "البرازيل سانتا لوكيا"],
  ["brazil wafer", "البرازيل وافير"],
  ["Brazilian Coffee Beans", "برازيلي قهوة بينس"],
  ["Bright Eye -- Speciality Blend", "بريغت ييي -- سبيكياليتي خلطة"],
  ["Broadway", "بروادواي"],
  ["Brunswick", "برونسويك"],
  ["Buena Vista Dark Roast", "بوينا فيستا داكن تحميص"],
  ["Buenos Dias", "بوينوس دياس"],
  ["Caramello", "كاراميللو"],
  ["Chakra", "تشاكرا"],
  ["Chelelektu", "تشيليليكتو"],
  ["Chire", "تشيري"],
  ["Churupallana 2026", "تشوروباللانا 2026"],
  ["cocoa caramel blend", "كوكوا كاراميل خلطة"],
  ["Colombia — Buesaco — Natural", "كولومبيا — بويساكو — طبيعي"],
  [
    "Colombia — Cerro Azul — Honey Geisha (Competition Series)",
    "كولومبيا — كيررو ازول — عسلي غيشا (كومبيتيتيون سيريس)",
  ],
  ["Colombia — Decaf", "كولومبيا — منزوع الكافيين"],
  ["Colombia Arcila - Anaerobic Honey", "كولومبيا اركيلا - لاهوائي عسلي"],
  [
    "Colombia Calderon - Anaerobic Natural",
    "كولومبيا كالديرون - لاهوائي طبيعي",
  ],
  ["Colombia Catiope Bourbon", "كولومبيا كاتيوبي بوربون"],
  ["Colombia Cauca natural", "كولومبيا كاوكا طبيعي"],
  [
    "Colombia Chambaku (Online Exclusive)",
    "كولومبيا تشامباكو (ونليني يكسكلوسيفي)",
  ],
  ["Colombia cherry", "كولومبيا كرز"],
  ["colombia coconut – mont blanco", "كولومبيا كوكونوت – مونت بلانكو"],
  ["Colombia Decaf", "كولومبيا منزوع الكافيين"],
  [
    "Colombia DECAF – TUMBAGA SUGARCANE",
    "كولومبيا منزوع الكافيين – تومباغا سوغاركاني",
  ],
  ["Colombia Decaf Coffee", "كولومبيا منزوع الكافيين قهوة"],
  ["Colombia El Mesón – Filter", "كولومبيا يل ميسون – ترشيح"],
  ["Colombia excelso", "كولومبيا يكسكيلسو"],
  [
    "Colombia Finca Zarza Fruit Forward Papayo Natural",
    "كولومبيا فينكا زارزا فاكهة فوروارد بابايو طبيعي",
  ],
  ["Colombia Geisha Marcela", "كولومبيا غيشا ماركيلا"],
  ["Colombia Giesha", "كولومبيا غيشا"],
  ["Colombia Hermides Meneses", "كولومبيا هيرميديس مينيسيس"],
  ["Colombia La Cristalina", "كولومبيا لا كريستالينا"],
  ["Colombia Laplata", "كولومبيا لابلاتا"],
  ["Colombia Las Palmas", "كولومبيا لاس بالماس"],
  ["colombia palladas natural", "كولومبيا باللاداس طبيعي"],
  ["Colombia Passion Fruit", "كولومبيا باشن فاكهة"],
  ["Colombia Passion Fruit – Mont Blanco", "كولومبيا باشن فاكهة – مونت بلانكو"],
  ["Colombia Sanchez Finca Monteblanco", "كولومبيا سانشيز فينكا مونتيبلانكو"],
  ["Colombia Santa Ana", "كولومبيا سانتا انا"],
  ["Colombia Sierra Nevada", "كولومبيا سيررا نيفادا"],
  ["Colombia Supremo", "كولومبيا سوبريمو"],
  ["Colombia Watermelon", "كولومبيا بطيخ"],
  ["Colombian Coffee Supremo", "كولومبي قهوة سوبريمو"],
  [
    "Costa Rica — Los Robles — Natural Reposado",
    "كوستاريكا — لوس روبليس — طبيعي ريبوسادو",
  ],
  ["Costa Rica Adelina Fallas Honey", "كوستاريكا اديلينا فاللاس عسلي"],
  ["Costa Rica Barátila", "كوستاريكا باراتيلا"],
  ["Costa Rica El Patalilo", "كوستاريكا يل باتاليلو"],
  [
    "Costa Rica Granitos - Ortiz 1800, Catuai, Yellow Honey",
    "كوستاريكا غرانيتوس - ورتيز 1800, كاتواي, أصفر عسلي",
  ],
  ["Costa Rica Las Lajas Natural", "كوستاريكا لاس لاجاس طبيعي"],
  ["costa rica Rio", "كوستاريكا ريو"],
  ["Cream Donut", "كريم دونوت"],
  ["Cumbres Decaffeinated", "كومبريس ديكاففييناتيد"],
  ["Dark Sugars", "داكن سوغارس"],
  ["Darkness -- Speciality Blend", "داركنيسس -- سبيكياليتي خلطة"],
  ["Dawn - Crafted Filter Blend", "داون - كرافتيد ترشيح خلطة"],
  ["Decaf", "منزوع الكافيين"],
  ["Desert -- Speciality Blend", "ديسيرت -- سبيكياليتي خلطة"],
  ["Dusk - Crafted Espresso Blend", "دوسك - كرافتيد إسبريسو خلطة"],
  [
    "Ecuador Finca La Aurum - Auction Lot",
    "الإكوادور فينكا لا اوروم - اوكتيون محصول",
  ],
  ["El Ángel", "يل Áنغيل"],
  ["El kaif -- Speciality Blend", "يل كايف -- سبيكياليتي خلطة"],
  ["El Salvador -- Gourmet", "السلفادور -- غورميت"],
  ["El Salvador -- Natural", "السلفادور -- طبيعي"],
  [
    "El Salvador — Finca Colombia — Natural Gesha",
    "السلفادور — فينكا كولومبيا — طبيعي غيشا",
  ],
  ["El Salvador Don Jaime", "السلفادور دون جايمي"],
  [
    "El Salvador Emerson Vasquez Pacamara",
    "السلفادور يميرسون فاسكويز باكامارا",
  ],
  [
    "El Salvador Finca Argentina, Yellow Pacamara, Natural",
    "السلفادور فينكا ارغينتينا, أصفر باكامارا, طبيعي",
  ],
  ["Elemental Coffee", "يليمينتال قهوة"],
  ["Elida Estate Torre", "يليدا يستاتي تورري"],
  ["Elixir - Brazil", "يليكسير - البرازيل"],
  ["Epic Espresso", "يبيك إسبريسو"],
  ["Ethiopia - Guji", "إثيوبيا - غوجي"],
  ["Ethiopia -- Guji", "إثيوبيا -- غوجي"],
  ["Ethiopia — Bench Maji — Natural", "إثيوبيا — بينتش ماجي — طبيعي"],
  ["Ethiopia Agaro Yukro G1", "إثيوبيا اغارو يوكرو G1"],
  ["Ethiopia anasora honey 89", "إثيوبيا اناسورا عسلي 89"],
  ["Ethiopia Aricha - Natural", "إثيوبيا أريشا - طبيعي"],
  ["Ethiopia Bisrat Melaku Washed", "إثيوبيا بيسرات ميلاكو مغسول"],
  ["Ethiopia Bona Zuria Fermented", "إثيوبيا بونا زوريا مخمّر"],
  ["Ethiopia Chelchele", "إثيوبيا تشيلتشيلي"],
  ["Ethiopia chelichele – yirgacheffe", "إثيوبيا تشيليتشيلي – ييرغاتشيففي"],
  ["Ethiopia Daye Bensa Hamasho Natural", "إثيوبيا دايي بينسا هاماشو طبيعي"],
  ["Ethiopia Goro Bedesa Fermented", "إثيوبيا غورو بيديسا مخمّر"],
  ["ethiopia gotiti super natural", "إثيوبيا غوتيتي سوبير طبيعي"],
  ["Ethiopia Guji — Filter", "إثيوبيا غوجي — ترشيح"],
  ["Ethiopia Guji Coffee Beans", "إثيوبيا غوجي قهوة بينس"],
  ["Ethiopia Guji G1 Masina", "إثيوبيا غوجي G1 ماسينا"],
  ["Ethiopia Guji Shakiso", "إثيوبيا غوجي شاكيسو"],
  ["Ethiopia Hambela Halaka", "إثيوبيا هامبيلا هالاكا"],
  ["ethiopia hambella", "إثيوبيا هامبيللا"],
  ["Ethiopia Hambella", "إثيوبيا هامبيللا"],
  ["Ethiopia Jininet", "إثيوبيا جينينيت"],
  ["Ethiopia Kello Lalesa – Filter", "إثيوبيا كيللو لاليسا – ترشيح"],
  ["Ethiopia Korma (Natural)", "إثيوبيا كورما (طبيعي)"],
  ["Ethiopia Rumudamo Anaerobic", "إثيوبيا رومودامو لاهوائي"],
  ["Ethiopia Sidamo anearobic", "إثيوبيا سيدامو انيروبيك"],
  ["Ethiopia Uraga", "إثيوبيا وراغا"],
  ["Ethiopia Yirgacheffe Beans", "إثيوبيا ييرغاتشيففي بينس"],
  ["Ethiopian Enaria", "إثيوبي يناريا"],
  ["Ex-Wife Espresso Blend", "يكس-ويفي إسبريسو خلطة"],
  ["Excelso (Colombia)", "يكسكيلسو (كولومبيا)"],
  ["Finca Ecuador – honey", "فينكا الإكوادور – عسلي"],
  ["Finca El Bosque", "فينكا يل بوسكوي"],
  ["Finca El Diviso", "فينكا يل ديفيسو"],
  ["Finca Tamana Caturron", "فينكا تامانا كاتوررون"],
  ["Freddy Mellado | Peru", "فريددي ميللادو | بيرو"],
  ["Funky Weekend Blend", "فونكي ويكيند خلطة"],
  ["Gachatha", "غاتشاثا"],
  ["Gargari Gutity G1 Red", "غارغاري غوتيتي G1 أحمر"],
  ["Geisha 72 Honey Process", "غيشا 72 عسلي معالجة"],
  ["Genesis Coffee", "غينيسيس قهوة"],
  ["Geometry", "غيوميتري"],
  ["Golden Waffle", "غولدين واففلي"],
  ["Guatemala Roast", "غواتيمالا تحميص"],
  ["Guayata", "غواياتا"],
  ["HABMELA - Ethiopia (HAMBELA)", "هابميلا - إثيوبيا (هامبيلا)"],
  ["Hambela Supernatural", "هامبيلا سوبيرناتورال"],
  ["Honduras Fredy Perez", "هندوراس فريدي بيريز"],
  ["India Single Origin Coffee Beans", "الهند أحادي المنشأ قهوة بينس"],
  [
    "Indonesia Frinsa Estate Weninggalih",
    "إندونيسيا فرينسا يستاتي وينينغغاليه",
  ],
  ["Indonesia Pantan Musara (Washed)", "إندونيسيا بانتان موسارا (مغسول)"],
  ["Jhenrry Chávez", "جهينرري تشافيز"],
  ["Juice Box", "جويكي بوكس"],
  ["Julian Calderón Pink Bourbon", "جوليان كالديرون وردي بوربون"],
  ["Kafipamba", "كافيبامبا"],
  ["Kaliluni AA", "كاليلوني AA"],
  ["Kamavindi Washed SL28 & SL34 AA", "كامافيندي مغسول SL28 & SL34 AA"],
  ["Kayon Mountain Natural Heirloom", "كايون مونتاين طبيعي سلالات محلية"],
  ["Kenya Anaerobic", "كينيا لاهوائي"],
  ["Kenya Gatomboya AB", "كينيا غاتومبويا AB"],
  ["Kenya Gicherori Washed", "كينيا غيتشيروري مغسول"],
  ["Kenya Kamunyaka AA", "كينيا كامونياكا AA"],
  ["Kenya Kangocho AA", "كينيا كانغوتشو AA"],
  ["Kenya Ruiruiru - Anaerobic Natural", "كينيا رويرويرو - لاهوائي طبيعي"],
  ["Kenya Sasha", "كينيا ساشا"],
  ["Kenya Thunguri AA – Filter", "كينيا ثونغوري AA – ترشيح"],
  ["Khayalah Mountain", "خايالاه مونتاين"],
  ["Kiambu Regional C", "كيامبو ريغيونال C"],
  ["Kii", "كيي"],
  ["La Plata Decaf", "لا بلاتا منزوع الكافيين"],
  ["La Torre Mejia Geisha", "لا تورري ميجيا غيشا"],
  ["Lalesa Ephtah", "لاليسا يفتاه"],
  [
    "Laymoon Twist (Costa Rica Red Honey)",
    "لايمون تويست (كوستاريكا أحمر عسلي)",
  ],
  ["Lollit (Ethiopia)", "لولليت (إثيوبيا)"],
  ["Los Colores | El Salvador", "لوس كولوريس | السلفادور"],
  ["Los Pirineos Pacamara", "لوس بيرينيوس باكامارا"],
  ["Maguta Estate Lot 432", "ماغوتا يستاتي محصول 432"],
  ["Maidy Bocanegra Pink Bourbon", "مايدي بوكانيغرا وردي بوربون"],
  ["Mameria Native Community | Peru", "ماميريا ناتيفي كوممونيتي | بيرو"],
  ["Maple", "مابلي"],
  ["Masar (Yemen)", "ماسار (اليمن)"],
  ["Meloraa (Costa Rica)", "ميلورا (كوستاريكا)"],
  ["Mexico Altura High Grown", "المكسيك التورا هيغ غروون"],
  ["Mexico Oaxaca Yogondoy Gesha", "المكسيك واكساكا يوغوندوي غيشا"],
  ["Midnight - Crafted Blend", "ميدنيغت - كرافتيد خلطة"],
  ["Milky Cake", "حليبي كيك"],
  ["Miramundo", "ميراموندو"],
  ["Mogiana", "موغيانا"],
  ["Monarch", "مونارتش"],
  ["Mystery -- Speciality Blend", "ميستيري -- سبيكياليتي خلطة"],
  ["Nardos (Ethiopia)", "ناردوس (إثيوبيا)"],
  ["Oasis Blend", "واسيس خلطة"],
  ["Old lady -- Speciality Blend", "ولد لادي -- سبيكياليتي خلطة"],
  ["Old School Espresso", "ولد سكول إسبريسو"],
  ["Organic Blend", "ورغانيك خلطة"],
  ["ORU Blend", "ورو خلطة"],
  ["Pacas 2026", "باكاس 2026"],
  [
    "Panama Finca Kotowa Silvia Marina Geisha Natural Lot 26-4320",
    "بنما فينكا كوتووا سيلفيا مارينا غيشا طبيعي محصول 26-4320",
  ],
  [
    "Panama Janson Coffee Geisha Washed Lot 26-178",
    "بنما جانسون قهوة غيشا مغسول محصول 26-178",
  ],
  ["Panama Janson Family Hacienda", "بنما جانسون فاميلي هاسييندا"],
  ["Papayo Hydro Natural", "بابايو هيدرو طبيعي"],
  ["Papua New Guinea Sigri Peaberry", "بابوا غينيا الجديدة سيغري بيبيرري"],
  ["Parainema 2026", "باراينيما 2026"],
  ["Peru - Cajamarca", "بيرو - كاجاماركا"],
  ["Peru La Margarita Gesha", "بيرو لا مارغاريتا غيشا"],
  ["Pillar", "بيللار"],
  [
    "PNG Keto Tapasi (2022 competition coffee)",
    "بنغ كيتو تاباسي (2022 كومبيتيتيون قهوة)",
  ],
  ["Power Nap", "بووير ناب"],
  ["Raspberry Candy", "راسببيرري كاندي"],
  ["Raspberry Candy Filter", "راسببيرري كاندي ترشيح"],
  ["Red Brick", "أحمر بريك"],
  ["Reset Half Caff", "ريسيت هالف كافف"],
  ["Rico", "ريكو"],
  ["Rivense La Guaca", "ريفينسي لا غواكا"],
  ["Rocko Mountain", "روكو مونتاين"],
  ["Romario — Brazil", "روماريو — البرازيل"],
  ["Rungeto C", "رونغيتو C"],
  [
    "Rwanda Mbilima Soil Project Lot.0704",
    "رواندا مبيليما سويل بروجيكت لوت.0704",
  ],
  ["Sagastume Typica 2023", "ساغاستومي تيبيكا 2023"],
  ["salvador Akato anearobic", "سالفادور اكاتو انيروبيك"],
  ["Salvador divisadero", "سالفادور ديفيساديرو"],
  ["Salvador Ruby", "سالفادور روبي"],
  ["Salvador Sarchimor", "سالفادور سارتشيمور"],
  ["Seabright House Blend", "سيبريغت المنزل خلطة"],
  ["Seasonal Espresso Blend", "سيسونال إسبريسو خلطة"],
  ["Sermon", "سيرمون"],
  ["Shantawene", "شانتاويني"],
  ["Shepherd -- Speciality Blend", "شيفيرد -- سبيكياليتي خلطة"],
  ["Silky Way", "سيلكي واي"],
  ["South Blend", "سوث خلطة"],
  ["Southern Weather", "سوثيرن ويثير"],
  ["Streetlevel", "ستريتليفيل"],
  ["Sunda Wanoja", "سوندا وانوجا"],
  ["SuperNatural Karibu", "سوبيرناتورال كاريبو"],
  ["Sweater Weather Blend", "سويتير ويثير خلطة"],
  ["Tadesse Washed Krume", "تاديسسي مغسول كرومي"],
  ["Thageini Indigo | Kenya", "ثاغييني ينديغو | كينيا"],
  ["The Alchemist", "الـ التشيميست"],
  ["The Answer", "الـ انسوير"],
  ["The Best Friends Blend", "الـ بيست فريندس خلطة"],
  ["Tropical Canopy | Ethiopia", "تروبيكال كانوبي | إثيوبيا"],
  ["Tropical Weather", "تروبيكال ويثير"],
  ["Twilight - Crafted Blend", "تويليغت - كرافتيد خلطة"],
  ["Uganda Elgon Anaerobic Natural", "أوغندا يلغون لاهوائي طبيعي"],
  ["uganda mama betty", "أوغندا ماما بيتتي"],
  ["Uganda Mukhoto", "أوغندا موخوتو"],
  ["Umoja Washed", "وموجا مغسول"],
  ["Volcan Azul Washed SL28", "فولكان ازول مغسول SL28"],
  ["Watad Mountain", "واتاد مونتاين"],
  ["Wild Arabian -- Speciality Blend", "وايلد عربي -- سبيكياليتي خلطة"],
  ["Wilderness -- Speciality Blend", "ويلديرنيسس -- سبيكياليتي خلطة"],
  ["Woolloomooloo", "ووللومولو"],
  ["Yemen - Kholani", "اليمن - خولاني"],
  ["Yemen – Anas – Anaerobic", "اليمن – اناس – لاهوائي"],
  ["Yemen Abu Wudiyyan", "اليمن ابو ووديييان"],
  ["yemen atarah anearobic", "اليمن اتاراه انيروبيك"],
  ["Yemen Muhammad Zidan - Natural", "اليمن موهامماد زيدان - طبيعي"],
  [
    "Yemen Rare Single Origin Coffee Beans",
    "اليمن راري أحادي المنشأ قهوة بينس",
  ],
  ["Yemen Shai'an Hiwar - Natural", "اليمن شاي'ان هيوار - طبيعي"],
  ["Yemen Shai'an Hiwar - Peaberry", "اليمن شاي'ان هيوار - بيبيرري"],
  ["Yirgacheffe Chelchele", "ييرغاتشيففي تشيلتشيلي"],
  ["Yirgacheffe Washed Halo Bariti", "ييرغاتشيففي مغسول هالو باريتي"],
  ["Yula Regional Lot", "يولا ريغيونال محصول"],
];
