// ISO 3166-1 regions; names from the Node.js ICU / Unicode CLDR dataset.
// Generated once; no network requests or Intl.DisplayNames support needed on phones.
export const accountCountries = [
  {"code": "AD", "ar": "أندورا", "en": "Andorra", "ja": "アンドラ"},
  {"code": "AE", "ar": "الإمارات العربية المتحدة", "en": "United Arab Emirates", "ja": "アラブ首長国連邦"},
  {"code": "AF", "ar": "أفغانستان", "en": "Afghanistan", "ja": "アフガニスタン"},
  {"code": "AG", "ar": "أنتيغوا وبربودا", "en": "Antigua & Barbuda", "ja": "アンティグア・バーブーダ"},
  {"code": "AI", "ar": "أنغويلا", "en": "Anguilla", "ja": "アンギラ"},
  {"code": "AL", "ar": "ألبانيا", "en": "Albania", "ja": "アルバニア"},
  {"code": "AM", "ar": "أرمينيا", "en": "Armenia", "ja": "アルメニア"},
  {"code": "AO", "ar": "أنغولا", "en": "Angola", "ja": "アンゴラ"},
  {"code": "AQ", "ar": "أنتاركتيكا", "en": "Antarctica", "ja": "南極"},
  {"code": "AR", "ar": "الأرجنتين", "en": "Argentina", "ja": "アルゼンチン"},
  {"code": "AS", "ar": "ساموا الأمريكية", "en": "American Samoa", "ja": "米領サモア"},
  {"code": "AT", "ar": "النمسا", "en": "Austria", "ja": "オーストリア"},
  {"code": "AU", "ar": "أستراليا", "en": "Australia", "ja": "オーストラリア"},
  {"code": "AW", "ar": "أروبا", "en": "Aruba", "ja": "アルバ"},
  {"code": "AX", "ar": "جزر آلاند", "en": "Åland Islands", "ja": "オーランド諸島"},
  {"code": "AZ", "ar": "أذربيجان", "en": "Azerbaijan", "ja": "アゼルバイジャン"},
  {"code": "BA", "ar": "البوسنة والهرسك", "en": "Bosnia & Herzegovina", "ja": "ボスニア・ヘルツェゴビナ"},
  {"code": "BB", "ar": "بربادوس", "en": "Barbados", "ja": "バルバドス"},
  {"code": "BD", "ar": "بنغلاديش", "en": "Bangladesh", "ja": "バングラデシュ"},
  {"code": "BE", "ar": "بلجيكا", "en": "Belgium", "ja": "ベルギー"},
  {"code": "BF", "ar": "بوركينا فاسو", "en": "Burkina Faso", "ja": "ブルキナファソ"},
  {"code": "BG", "ar": "بلغاريا", "en": "Bulgaria", "ja": "ブルガリア"},
  {"code": "BH", "ar": "البحرين", "en": "Bahrain", "ja": "バーレーン"},
  {"code": "BI", "ar": "بوروندي", "en": "Burundi", "ja": "ブルンジ"},
  {"code": "BJ", "ar": "بنين", "en": "Benin", "ja": "ベナン"},
  {"code": "BL", "ar": "سان بارتليمي", "en": "St. Barthélemy", "ja": "サン・バルテルミー"},
  {"code": "BM", "ar": "برمودا", "en": "Bermuda", "ja": "バミューダ"},
  {"code": "BN", "ar": "بروناي", "en": "Brunei", "ja": "ブルネイ"},
  {"code": "BO", "ar": "بوليفيا", "en": "Bolivia", "ja": "ボリビア"},
  {"code": "BQ", "ar": "هولندا الكاريبية", "en": "Caribbean Netherlands", "ja": "オランダ領カリブ"},
  {"code": "BR", "ar": "البرازيل", "en": "Brazil", "ja": "ブラジル"},
  {"code": "BS", "ar": "جزر البهاما", "en": "Bahamas", "ja": "バハマ"},
  {"code": "BT", "ar": "بوتان", "en": "Bhutan", "ja": "ブータン"},
  {"code": "BV", "ar": "جزيرة بوفيه", "en": "Bouvet Island", "ja": "ブーベ島"},
  {"code": "BW", "ar": "بوتسوانا", "en": "Botswana", "ja": "ボツワナ"},
  {"code": "BY", "ar": "بيلاروس", "en": "Belarus", "ja": "ベラルーシ"},
  {"code": "BZ", "ar": "بليز", "en": "Belize", "ja": "ベリーズ"},
  {"code": "CA", "ar": "كندا", "en": "Canada", "ja": "カナダ"},
  {"code": "CC", "ar": "جزر كوكوس (كيلينغ)", "en": "Cocos (Keeling) Islands", "ja": "ココス(キーリング)諸島"},
  {"code": "CD", "ar": "الكونغو - كينشاسا", "en": "Congo - Kinshasa", "ja": "コンゴ民主共和国(キンシャサ)"},
  {"code": "CF", "ar": "جمهورية أفريقيا الوسطى", "en": "Central African Republic", "ja": "中央アフリカ共和国"},
  {"code": "CG", "ar": "الكونغو - برازافيل", "en": "Congo - Brazzaville", "ja": "コンゴ共和国(ブラザビル)"},
  {"code": "CH", "ar": "سويسرا", "en": "Switzerland", "ja": "スイス"},
  {"code": "CI", "ar": "ساحل العاج", "en": "Côte d’Ivoire", "ja": "コートジボワール"},
  {"code": "CK", "ar": "جزر كوك", "en": "Cook Islands", "ja": "クック諸島"},
  {"code": "CL", "ar": "تشيلي", "en": "Chile", "ja": "チリ"},
  {"code": "CM", "ar": "الكاميرون", "en": "Cameroon", "ja": "カメルーン"},
  {"code": "CN", "ar": "الصين", "en": "China", "ja": "中国"},
  {"code": "CO", "ar": "كولومبيا", "en": "Colombia", "ja": "コロンビア"},
  {"code": "CR", "ar": "كوستاريكا", "en": "Costa Rica", "ja": "コスタリカ"},
  {"code": "CU", "ar": "كوبا", "en": "Cuba", "ja": "キューバ"},
  {"code": "CV", "ar": "الرأس الأخضر", "en": "Cape Verde", "ja": "カーボベルデ"},
  {"code": "CW", "ar": "كوراساو", "en": "Curaçao", "ja": "キュラソー"},
  {"code": "CX", "ar": "جزيرة كريسماس", "en": "Christmas Island", "ja": "クリスマス島"},
  {"code": "CY", "ar": "قبرص", "en": "Cyprus", "ja": "キプロス"},
  {"code": "CZ", "ar": "التشيك", "en": "Czechia", "ja": "チェコ"},
  {"code": "DE", "ar": "ألمانيا", "en": "Germany", "ja": "ドイツ"},
  {"code": "DJ", "ar": "جيبوتي", "en": "Djibouti", "ja": "ジブチ"},
  {"code": "DK", "ar": "الدانمرك", "en": "Denmark", "ja": "デンマーク"},
  {"code": "DM", "ar": "دومينيكا", "en": "Dominica", "ja": "ドミニカ国"},
  {"code": "DO", "ar": "جمهورية الدومينيكان", "en": "Dominican Republic", "ja": "ドミニカ共和国"},
  {"code": "DZ", "ar": "الجزائر", "en": "Algeria", "ja": "アルジェリア"},
  {"code": "EC", "ar": "الإكوادور", "en": "Ecuador", "ja": "エクアドル"},
  {"code": "EE", "ar": "إستونيا", "en": "Estonia", "ja": "エストニア"},
  {"code": "EG", "ar": "مصر", "en": "Egypt", "ja": "エジプト"},
  {"code": "EH", "ar": "الصحراء الغربية", "en": "Western Sahara", "ja": "西サハラ"},
  {"code": "ER", "ar": "إريتريا", "en": "Eritrea", "ja": "エリトリア"},
  {"code": "ES", "ar": "إسبانيا", "en": "Spain", "ja": "スペイン"},
  {"code": "ET", "ar": "إثيوبيا", "en": "Ethiopia", "ja": "エチオピア"},
  {"code": "FI", "ar": "فنلندا", "en": "Finland", "ja": "フィンランド"},
  {"code": "FJ", "ar": "فيجي", "en": "Fiji", "ja": "フィジー"},
  {"code": "FK", "ar": "جزر فوكلاند", "en": "Falkland Islands", "ja": "フォークランド諸島"},
  {"code": "FM", "ar": "ميكرونيزيا", "en": "Micronesia", "ja": "ミクロネシア連邦"},
  {"code": "FO", "ar": "جزر فارو", "en": "Faroe Islands", "ja": "フェロー諸島"},
  {"code": "FR", "ar": "فرنسا", "en": "France", "ja": "フランス"},
  {"code": "GA", "ar": "الغابون", "en": "Gabon", "ja": "ガボン"},
  {"code": "GB", "ar": "المملكة المتحدة", "en": "United Kingdom", "ja": "イギリス"},
  {"code": "GD", "ar": "غرينادا", "en": "Grenada", "ja": "グレナダ"},
  {"code": "GE", "ar": "جورجيا", "en": "Georgia", "ja": "ジョージア"},
  {"code": "GF", "ar": "غويانا الفرنسية", "en": "French Guiana", "ja": "仏領ギアナ"},
  {"code": "GG", "ar": "غيرنزي", "en": "Guernsey", "ja": "ガーンジー"},
  {"code": "GH", "ar": "غانا", "en": "Ghana", "ja": "ガーナ"},
  {"code": "GI", "ar": "جبل طارق", "en": "Gibraltar", "ja": "ジブラルタル"},
  {"code": "GL", "ar": "غرينلاند", "en": "Greenland", "ja": "グリーンランド"},
  {"code": "GM", "ar": "غامبيا", "en": "Gambia", "ja": "ガンビア"},
  {"code": "GN", "ar": "غينيا", "en": "Guinea", "ja": "ギニア"},
  {"code": "GP", "ar": "غوادلوب", "en": "Guadeloupe", "ja": "グアドループ"},
  {"code": "GQ", "ar": "غينيا الاستوائية", "en": "Equatorial Guinea", "ja": "赤道ギニア"},
  {"code": "GR", "ar": "اليونان", "en": "Greece", "ja": "ギリシャ"},
  {"code": "GS", "ar": "جورجيا الجنوبية وجزر ساندويتش الجنوبية", "en": "South Georgia & South Sandwich Islands", "ja": "サウスジョージア・サウスサンドウィッチ諸島"},
  {"code": "GT", "ar": "غواتيمالا", "en": "Guatemala", "ja": "グアテマラ"},
  {"code": "GU", "ar": "غوام", "en": "Guam", "ja": "グアム"},
  {"code": "GW", "ar": "غينيا بيساو", "en": "Guinea-Bissau", "ja": "ギニアビサウ"},
  {"code": "GY", "ar": "غيانا", "en": "Guyana", "ja": "ガイアナ"},
  {"code": "HK", "ar": "هونغ كونغ الصينية (منطقة إدارية خاصة)", "en": "Hong Kong SAR China", "ja": "中華人民共和国香港特別行政区"},
  {"code": "HM", "ar": "جزيرة هيرد وجزر ماكدونالد", "en": "Heard & McDonald Islands", "ja": "ハード島・マクドナルド諸島"},
  {"code": "HN", "ar": "هندوراس", "en": "Honduras", "ja": "ホンジュラス"},
  {"code": "HR", "ar": "كرواتيا", "en": "Croatia", "ja": "クロアチア"},
  {"code": "HT", "ar": "هايتي", "en": "Haiti", "ja": "ハイチ"},
  {"code": "HU", "ar": "هنغاريا", "en": "Hungary", "ja": "ハンガリー"},
  {"code": "ID", "ar": "إندونيسيا", "en": "Indonesia", "ja": "インドネシア"},
  {"code": "IE", "ar": "أيرلندا", "en": "Ireland", "ja": "アイルランド"},
  {"code": "IL", "ar": "إسرائيل", "en": "Israel", "ja": "イスラエル"},
  {"code": "IM", "ar": "جزيرة مان", "en": "Isle of Man", "ja": "マン島"},
  {"code": "IN", "ar": "الهند", "en": "India", "ja": "インド"},
  {"code": "IO", "ar": "الإقليم البريطاني في المحيط الهندي", "en": "British Indian Ocean Territory", "ja": "英領インド洋地域"},
  {"code": "IQ", "ar": "العراق", "en": "Iraq", "ja": "イラク"},
  {"code": "IR", "ar": "إيران", "en": "Iran", "ja": "イラン"},
  {"code": "IS", "ar": "آيسلندا", "en": "Iceland", "ja": "アイスランド"},
  {"code": "IT", "ar": "إيطاليا", "en": "Italy", "ja": "イタリア"},
  {"code": "JE", "ar": "جيرسي", "en": "Jersey", "ja": "ジャージー"},
  {"code": "JM", "ar": "جامايكا", "en": "Jamaica", "ja": "ジャマイカ"},
  {"code": "JO", "ar": "الأردن", "en": "Jordan", "ja": "ヨルダン"},
  {"code": "JP", "ar": "اليابان", "en": "Japan", "ja": "日本"},
  {"code": "KE", "ar": "كينيا", "en": "Kenya", "ja": "ケニア"},
  {"code": "KG", "ar": "قيرغيزستان", "en": "Kyrgyzstan", "ja": "キルギス"},
  {"code": "KH", "ar": "كمبوديا", "en": "Cambodia", "ja": "カンボジア"},
  {"code": "KI", "ar": "كيريباتي", "en": "Kiribati", "ja": "キリバス"},
  {"code": "KM", "ar": "جزر القمر", "en": "Comoros", "ja": "コモロ"},
  {"code": "KN", "ar": "سانت كيتس ونيفيس", "en": "St. Kitts & Nevis", "ja": "セントクリストファー・ネーヴィス"},
  {"code": "KP", "ar": "كوريا الشمالية", "en": "North Korea", "ja": "北朝鮮"},
  {"code": "KR", "ar": "كوريا الجنوبية", "en": "South Korea", "ja": "韓国"},
  {"code": "KW", "ar": "الكويت", "en": "Kuwait", "ja": "クウェート"},
  {"code": "KY", "ar": "جزر كايمان", "en": "Cayman Islands", "ja": "ケイマン諸島"},
  {"code": "KZ", "ar": "كازاخستان", "en": "Kazakhstan", "ja": "カザフスタン"},
  {"code": "LA", "ar": "لاوس", "en": "Laos", "ja": "ラオス"},
  {"code": "LB", "ar": "لبنان", "en": "Lebanon", "ja": "レバノン"},
  {"code": "LC", "ar": "سانت لوسيا", "en": "St. Lucia", "ja": "セントルシア"},
  {"code": "LI", "ar": "ليختنشتاين", "en": "Liechtenstein", "ja": "リヒテンシュタイン"},
  {"code": "LK", "ar": "سريلانكا", "en": "Sri Lanka", "ja": "スリランカ"},
  {"code": "LR", "ar": "ليبيريا", "en": "Liberia", "ja": "リベリア"},
  {"code": "LS", "ar": "ليسوتو", "en": "Lesotho", "ja": "レソト"},
  {"code": "LT", "ar": "ليتوانيا", "en": "Lithuania", "ja": "リトアニア"},
  {"code": "LU", "ar": "لوكسمبورغ", "en": "Luxembourg", "ja": "ルクセンブルク"},
  {"code": "LV", "ar": "لاتفيا", "en": "Latvia", "ja": "ラトビア"},
  {"code": "LY", "ar": "ليبيا", "en": "Libya", "ja": "リビア"},
  {"code": "MA", "ar": "المغرب", "en": "Morocco", "ja": "モロッコ"},
  {"code": "MC", "ar": "موناكو", "en": "Monaco", "ja": "モナコ"},
  {"code": "MD", "ar": "مولدوفا", "en": "Moldova", "ja": "モルドバ"},
  {"code": "ME", "ar": "الجبل الأسود", "en": "Montenegro", "ja": "モンテネグロ"},
  {"code": "MF", "ar": "سان مارتن", "en": "St. Martin", "ja": "サン・マルタン"},
  {"code": "MG", "ar": "مدغشقر", "en": "Madagascar", "ja": "マダガスカル"},
  {"code": "MH", "ar": "جزر مارشال", "en": "Marshall Islands", "ja": "マーシャル諸島"},
  {"code": "MK", "ar": "مقدونيا الشمالية", "en": "North Macedonia", "ja": "北マケドニア"},
  {"code": "ML", "ar": "مالي", "en": "Mali", "ja": "マリ"},
  {"code": "MM", "ar": "ميانمار (بورما)", "en": "Myanmar (Burma)", "ja": "ミャンマー (ビルマ)"},
  {"code": "MN", "ar": "منغوليا", "en": "Mongolia", "ja": "モンゴル"},
  {"code": "MO", "ar": "منطقة ماكاو الإدارية الخاصة", "en": "Macao SAR China", "ja": "中華人民共和国マカオ特別行政区"},
  {"code": "MP", "ar": "جزر ماريانا الشمالية", "en": "Northern Mariana Islands", "ja": "北マリアナ諸島"},
  {"code": "MQ", "ar": "جزر المارتينيك", "en": "Martinique", "ja": "マルティニーク"},
  {"code": "MR", "ar": "موريتانيا", "en": "Mauritania", "ja": "モーリタニア"},
  {"code": "MS", "ar": "مونتسرات", "en": "Montserrat", "ja": "モントセラト"},
  {"code": "MT", "ar": "مالطا", "en": "Malta", "ja": "マルタ"},
  {"code": "MU", "ar": "موريشيوس", "en": "Mauritius", "ja": "モーリシャス"},
  {"code": "MV", "ar": "جزر المالديف", "en": "Maldives", "ja": "モルディブ"},
  {"code": "MW", "ar": "ملاوي", "en": "Malawi", "ja": "マラウイ"},
  {"code": "MX", "ar": "المكسيك", "en": "Mexico", "ja": "メキシコ"},
  {"code": "MY", "ar": "ماليزيا", "en": "Malaysia", "ja": "マレーシア"},
  {"code": "MZ", "ar": "موزمبيق", "en": "Mozambique", "ja": "モザンビーク"},
  {"code": "NA", "ar": "ناميبيا", "en": "Namibia", "ja": "ナミビア"},
  {"code": "NC", "ar": "كاليدونيا الجديدة", "en": "New Caledonia", "ja": "ニューカレドニア"},
  {"code": "NE", "ar": "النيجر", "en": "Niger", "ja": "ニジェール"},
  {"code": "NF", "ar": "جزيرة نورفولك", "en": "Norfolk Island", "ja": "ノーフォーク島"},
  {"code": "NG", "ar": "نيجيريا", "en": "Nigeria", "ja": "ナイジェリア"},
  {"code": "NI", "ar": "نيكاراغوا", "en": "Nicaragua", "ja": "ニカラグア"},
  {"code": "NL", "ar": "هولندا", "en": "Netherlands", "ja": "オランダ"},
  {"code": "NO", "ar": "النرويج", "en": "Norway", "ja": "ノルウェー"},
  {"code": "NP", "ar": "نيبال", "en": "Nepal", "ja": "ネパール"},
  {"code": "NR", "ar": "ناورو", "en": "Nauru", "ja": "ナウル"},
  {"code": "NU", "ar": "نيوي", "en": "Niue", "ja": "ニウエ"},
  {"code": "NZ", "ar": "نيوزيلندا", "en": "New Zealand", "ja": "ニュージーランド"},
  {"code": "OM", "ar": "عُمان", "en": "Oman", "ja": "オマーン"},
  {"code": "PA", "ar": "بنما", "en": "Panama", "ja": "パナマ"},
  {"code": "PE", "ar": "بيرو", "en": "Peru", "ja": "ペルー"},
  {"code": "PF", "ar": "بولينيزيا الفرنسية", "en": "French Polynesia", "ja": "仏領ポリネシア"},
  {"code": "PG", "ar": "بابوا غينيا الجديدة", "en": "Papua New Guinea", "ja": "パプアニューギニア"},
  {"code": "PH", "ar": "الفلبين", "en": "Philippines", "ja": "フィリピン"},
  {"code": "PK", "ar": "باكستان", "en": "Pakistan", "ja": "パキスタン"},
  {"code": "PL", "ar": "بولندا", "en": "Poland", "ja": "ポーランド"},
  {"code": "PM", "ar": "سان بيير ومكويلون", "en": "St. Pierre & Miquelon", "ja": "サンピエール島・ミクロン島"},
  {"code": "PN", "ar": "جزر بيتكيرن", "en": "Pitcairn Islands", "ja": "ピトケアン諸島"},
  {"code": "PR", "ar": "بورتوريكو", "en": "Puerto Rico", "ja": "プエルトリコ"},
  {"code": "PS", "ar": "الأراضي الفلسطينية", "en": "Palestinian Territories", "ja": "パレスチナ自治区"},
  {"code": "PT", "ar": "البرتغال", "en": "Portugal", "ja": "ポルトガル"},
  {"code": "PW", "ar": "بالاو", "en": "Palau", "ja": "パラオ"},
  {"code": "PY", "ar": "باراغواي", "en": "Paraguay", "ja": "パラグアイ"},
  {"code": "QA", "ar": "قطر", "en": "Qatar", "ja": "カタール"},
  {"code": "RE", "ar": "روينيون", "en": "Réunion", "ja": "レユニオン"},
  {"code": "RO", "ar": "رومانيا", "en": "Romania", "ja": "ルーマニア"},
  {"code": "RS", "ar": "صربيا", "en": "Serbia", "ja": "セルビア"},
  {"code": "RU", "ar": "روسيا", "en": "Russia", "ja": "ロシア"},
  {"code": "RW", "ar": "رواندا", "en": "Rwanda", "ja": "ルワンダ"},
  {"code": "SA", "ar": "المملكة العربية السعودية", "en": "Saudi Arabia", "ja": "サウジアラビア"},
  {"code": "SB", "ar": "جزر سليمان", "en": "Solomon Islands", "ja": "ソロモン諸島"},
  {"code": "SC", "ar": "سيشل", "en": "Seychelles", "ja": "セーシェル"},
  {"code": "SD", "ar": "السودان", "en": "Sudan", "ja": "スーダン"},
  {"code": "SE", "ar": "السويد", "en": "Sweden", "ja": "スウェーデン"},
  {"code": "SG", "ar": "سنغافورة", "en": "Singapore", "ja": "シンガポール"},
  {"code": "SH", "ar": "سانت هيلينا", "en": "St. Helena", "ja": "セントヘレナ"},
  {"code": "SI", "ar": "سلوفينيا", "en": "Slovenia", "ja": "スロベニア"},
  {"code": "SJ", "ar": "سفالبارد وجان ماين", "en": "Svalbard & Jan Mayen", "ja": "スバールバル諸島・ヤンマイエン島"},
  {"code": "SK", "ar": "سلوفاكيا", "en": "Slovakia", "ja": "スロバキア"},
  {"code": "SL", "ar": "سيراليون", "en": "Sierra Leone", "ja": "シエラレオネ"},
  {"code": "SM", "ar": "سان مارينو", "en": "San Marino", "ja": "サンマリノ"},
  {"code": "SN", "ar": "السنغال", "en": "Senegal", "ja": "セネガル"},
  {"code": "SO", "ar": "الصومال", "en": "Somalia", "ja": "ソマリア"},
  {"code": "SR", "ar": "سورينام", "en": "Suriname", "ja": "スリナム"},
  {"code": "SS", "ar": "جنوب السودان", "en": "South Sudan", "ja": "南スーダン"},
  {"code": "ST", "ar": "ساو تومي وبرينسيبي", "en": "São Tomé & Príncipe", "ja": "サントメ・プリンシペ"},
  {"code": "SV", "ar": "السلفادور", "en": "El Salvador", "ja": "エルサルバドル"},
  {"code": "SX", "ar": "سانت مارتن", "en": "Sint Maarten", "ja": "シント・マールテン"},
  {"code": "SY", "ar": "سوريا", "en": "Syria", "ja": "シリア"},
  {"code": "SZ", "ar": "إسواتيني", "en": "Eswatini", "ja": "エスワティニ"},
  {"code": "TC", "ar": "جزر توركس وكايكوس", "en": "Turks & Caicos Islands", "ja": "タークス・カイコス諸島"},
  {"code": "TD", "ar": "تشاد", "en": "Chad", "ja": "チャド"},
  {"code": "TF", "ar": "الأقاليم الجنوبية الفرنسية", "en": "French Southern Territories", "ja": "仏領極南諸島"},
  {"code": "TG", "ar": "توغو", "en": "Togo", "ja": "トーゴ"},
  {"code": "TH", "ar": "تايلاند", "en": "Thailand", "ja": "タイ"},
  {"code": "TJ", "ar": "طاجيكستان", "en": "Tajikistan", "ja": "タジキスタン"},
  {"code": "TK", "ar": "توكيلاو", "en": "Tokelau", "ja": "トケラウ"},
  {"code": "TL", "ar": "تيمور - ليشتي", "en": "Timor-Leste", "ja": "東ティモール"},
  {"code": "TM", "ar": "تركمانستان", "en": "Turkmenistan", "ja": "トルクメニスタン"},
  {"code": "TN", "ar": "تونس", "en": "Tunisia", "ja": "チュニジア"},
  {"code": "TO", "ar": "تونغا", "en": "Tonga", "ja": "トンガ"},
  {"code": "TR", "ar": "تركيا", "en": "Türkiye", "ja": "トルコ"},
  {"code": "TT", "ar": "ترينيداد وتوباغو", "en": "Trinidad & Tobago", "ja": "トリニダード・トバゴ"},
  {"code": "TV", "ar": "توفالو", "en": "Tuvalu", "ja": "ツバル"},
  {"code": "TW", "ar": "تايوان", "en": "Taiwan", "ja": "台湾"},
  {"code": "TZ", "ar": "تنزانيا", "en": "Tanzania", "ja": "タンザニア"},
  {"code": "UA", "ar": "أوكرانيا", "en": "Ukraine", "ja": "ウクライナ"},
  {"code": "UG", "ar": "أوغندا", "en": "Uganda", "ja": "ウガンダ"},
  {"code": "UM", "ar": "جزر الولايات المتحدة النائية", "en": "U.S. Outlying Islands", "ja": "合衆国領有小離島"},
  {"code": "US", "ar": "الولايات المتحدة", "en": "United States", "ja": "アメリカ合衆国"},
  {"code": "UY", "ar": "أورغواي", "en": "Uruguay", "ja": "ウルグアイ"},
  {"code": "UZ", "ar": "أوزبكستان", "en": "Uzbekistan", "ja": "ウズベキスタン"},
  {"code": "VA", "ar": "الفاتيكان", "en": "Vatican City", "ja": "バチカン市国"},
  {"code": "VC", "ar": "سانت فنسنت وجزر غرينادين", "en": "St. Vincent & Grenadines", "ja": "セントビンセント及びグレナディーン諸島"},
  {"code": "VE", "ar": "فنزويلا", "en": "Venezuela", "ja": "ベネズエラ"},
  {"code": "VG", "ar": "جزر فيرجن البريطانية", "en": "British Virgin Islands", "ja": "英領ヴァージン諸島"},
  {"code": "VI", "ar": "جزر فيرجن الأمريكية", "en": "U.S. Virgin Islands", "ja": "米領ヴァージン諸島"},
  {"code": "VN", "ar": "فيتنام", "en": "Vietnam", "ja": "ベトナム"},
  {"code": "VU", "ar": "فانواتو", "en": "Vanuatu", "ja": "バヌアツ"},
  {"code": "WF", "ar": "جزر والس وفوتونا", "en": "Wallis & Futuna", "ja": "ウォリス・フツナ"},
  {"code": "WS", "ar": "ساموا", "en": "Samoa", "ja": "サモア"},
  {"code": "YE", "ar": "اليمن", "en": "Yemen", "ja": "イエメン"},
  {"code": "YT", "ar": "مايوت", "en": "Mayotte", "ja": "マヨット"},
  {"code": "ZA", "ar": "جنوب أفريقيا", "en": "South Africa", "ja": "南アフリカ"},
  {"code": "ZM", "ar": "زامبيا", "en": "Zambia", "ja": "ザンビア"},
  {"code": "ZW", "ar": "زيمبابوي", "en": "Zimbabwe", "ja": "ジンバブエ"},
] as const;
