/** Editorial lessons, reviewed 2026-10-09. Model settings belong to their manuals. */
export type CoffeeCourseGroup = 'beans' | 'grinding' | 'water' | 'equipment' | 'brewing' | 'roasting' | 'sensory';
export interface CoffeeLesson {
  id: string; group: CoffeeCourseGroup; titles: [string, string]; keywords: RegExp; priority: number;
  ar: string; en: string; more: [string, string]; title: string; url: string;
}
export const COFFEE_CURRICULUM: CoffeeLesson[] = [
  {
    id: 'coffee-basics', group: 'beans', titles: ['من الشجرة إلى الكوب', 'From seed to cup'], priority: 20,
    keywords: /ما هي القهوه|شنو القهوه|شجره|كرزه|seed to cup|coffee cherry|what is coffee/,
    ar: 'حبة القهوة بذرة داخل كرزة. يحدد الصنف والبيئة والنضج والمعالجة نقطة البداية، ثم يصنع التحميص الروائح ويستخلصها الماء. اسم البلد وحده لا يضمن إيحاءًا محددًا؛ اقرأ بيانات المحصول ثم تذوقه.',
    en: 'A coffee bean is a seed inside a cherry. Variety, environment, ripeness and processing shape the raw material; roasting creates aromas and brewing extracts them. A country name alone does not guarantee a flavor note. Read the lot information, then taste it.',
    more: ['قارن محصولين بوصفة واحدة، وسجل الصنف والمعالجة والتحميص وتاريخ التحضير. هذا يفصل أثر البن عن اختلاف وصفتك.', 'Compare two lots using one recipe. Record variety, processing, roast and brew date to separate coffee differences from recipe changes.'],
    title: 'NCA — What is coffee?', url: 'https://www.aboutcoffee.org/origins/what-is-coffee/',
  },
  {
    id: 'varieties', group: 'beans', titles: ['أرابيكا وروبوستا والأصناف', 'Species and varieties'], priority: 60,
    keywords: /ارابيكا|روبوستا|جيشا|بوربون|تيبيكا|سلال|صنف البن|arabica|robusta|gesha|bourbon|typica|variet/,
    ar: 'أرابيكا وروبوستا نوعان نباتيان؛ جيشا وبوربون وتيبيكا أصناف داخل أرابيكا. الصنف يؤثر في القابلية الزراعية والطعم، لكن المنشأ والمعالجة والتحميص عوامل مشتركة. اسم الصنف وحده ليس تقييمًا للجودة.',
    en: 'Arabica and robusta are species; Gesha, Bourbon and Typica are arabica varieties. Variety affects agronomic traits and flavor potential, alongside origin, processing and roast. A variety name alone is not a quality score.',
    more: ['اقرأ بطاقة المحصول كاملة بدل اختيار البن من اسم الصنف فقط، وقارن وصف المحمصة بما تتذوقه.', 'Read the complete lot card rather than buying only by variety. Compare the roaster’s description with your own tasting.'],
    title: 'World Coffee Research — Varieties', url: 'https://varieties.worldcoffeeresearch.org/',
  },
  {
    id: 'green-coffee', group: 'beans', titles: ['اختيار البن الأخضر', 'Choosing green coffee'], priority: 65,
    keywords: /بن اخضر|البن الاخضر|حبه خضرا|green (?:bean|coffee)|moisture|كثافه البن|رطوبه البن/,
    ar: 'قبل التحميص، سجل المنشأ والصنف والمعالجة والمحصول والرطوبة والكثافة إن كانت مقاسة. افحص التجانس والعيوب ورائحة العينة. الأخضر قد يكون مائلًا للرمادي أو الأصفر، والديكاف قد يبدأ بنيًا؛ اللون وحده لا يثبت النضارة أو الجودة.',
    en: 'Before roasting, record origin, variety, process, lot, moisture and density when measured. Inspect uniformity, defects and sample aroma. Green coffee can look grayish or yellowish; decaf can start brown. Color alone does not establish freshness or quality.',
    more: ['استخدم نفس المحصول ووزن الدفعة في تجربة التحميص. لا تنقل إعداد حمصة ناجحة إلى بن مختلف دون تجربة جديدة.', 'Keep the same lot and batch weight during roast experiments. Do not transfer a successful profile to a different coffee without another trial.'],
    title: 'SCA — Physical coffee assessment', url: 'https://sca.coffee/value-assessment',
  },
  {
    id: 'decaf', group: 'beans', titles: ['القهوة منزوعة الكافيين', 'Decaffeinated coffee'], priority: 70,
    keywords: /ديكاف|منزوع.*كافيين|بدون كافيين|decaf|decaffein/,
    ar: 'إزالة الكافيين تتم عادة قبل التحميص بعمليات مختلفة، والديكاف ليس خاليًا تمامًا من الكافيين. المعالجة تغيّر شكل البن وسلوكه؛ لا تحكم على درجة حمصته من لون الحبة وحده ولا تنسخ طحن البن العادي مباشرة.',
    en: 'Decaffeination generally happens before roasting, using different processes. Decaf still contains some caffeine. Processing changes bean appearance and behavior; do not judge its roast solely by color or copy another coffee’s grind setting.',
    more: ['ابدأ بتوصية المحمصة، ثم سجل الطعم وتدفق التحضير. عدّل خطوة واحدة مع تثبيت الجرعة والناتج.', 'Start with the roaster’s advice and record taste and brew flow. Change one variable with dose and yield held fixed.'],
    title: 'NCA — Decaf', url: 'https://www.aboutcoffee.org/beans/decaf-coffee/',
  },
  {
    id: 'grind-size', group: 'grinding', titles: ['درجة الطحن حسب التحضير', 'Grind size by method'], priority: 15,
    keywords: /طحن|طحنه|طاحون|مطحن|grind|grinder/,
    ar: 'الإسبريسو يحتاج عادة طحنًا أنعم من الترشيح، لكن الوصفة والأداة والبن تحدد الضبط. النعومة تزيد المساحة المعرضة للماء وقد تبطئ التدفق. ابدأ من دليل طاحونتك، وثبّت الجرعة والنسبة ثم غيّر الطحن قليلًا وتذوق. رقم الطاحونة ليس وحدة مشتركة بين الموديلات.',
    en: 'Espresso usually needs a finer grind than filter brewing, but brewer, recipe and coffee determine the setting. Finer particles increase exposed surface and can slow flow. Start with your grinder guide, keep dose and ratio fixed and make small changes by taste. Grinder numbers are not transferable units.',
    more: ['إذا صار التدفق غير منتظم، راجع التوزيع والفلاتر قبل زيادة النعومة. أعطني موديل الطاحونة وطريقة التحضير حتى نرجع لإرشادات الموديل.', 'If flow becomes uneven, check distribution and filters before grinding finer. Give the grinder model and brewing method to consult its guidance.'],
    title: 'Barista Hustle — Grind size', url: 'https://www.baristahustle.com/lesson/ae-1-03-grind-size/',
  },
  {
    id: 'burrs', group: 'grinding', titles: ['التروس المسطحة والمخروطية', 'Flat and conical burrs'], priority: 70,
    keywords: /تروس|مسطح|مخروط|flat burr|conical burr|burr geometry/,
    ar: 'التروس المسطحة والمخروطية هندستان للطحن، ولا تضمن إحداهما كوبًا أفضل دائمًا. شكل الأسنان والمحاذاة والسرعة والبن يؤثر في توزيع الجسيمات. اختر طاحونة تناسب الإسبريسو أو الترشيح، وتحقق من مدى الضبط والصيانة والاحتباس.',
    en: 'Flat and conical burrs are different grinding geometries; neither guarantees a better cup. Tooth design, alignment, speed and coffee influence particle distribution. Choose for espresso or filter use, then check adjustment range, serviceability and retention.',
    more: ['للمقارنة، اضبط كل طاحونة لأفضل طعم بدل استخدام نفس رقم الطحن. سجل الوصفة والجرعة والناتج والتكرار.', 'Dial each grinder for its best taste rather than comparing the same dial number. Record recipe, dose, output and repeatability.'],
    title: 'Barista Hustle — Grinding methods', url: 'https://www.baristahustle.com/lesson/ae-1-02-grinding-methods/',
  },
  {
    id: 'grinder-calibration', group: 'grinding', titles: ['الصفر والكليكات والمعايرة', 'Zero, clicks and calibration'], priority: 90,
    keywords: /كليك|نقره|صفر الطاحون|(?:معاير|اعاير|عاير).*طاحون|calibrat.*grind|grind.*calibrat|click|zero point|red clix/,
    ar: 'الصفر والكليكات يتبعان موديل الطاحونة وإصدار التروس. في C40 القياسية، توصيات Comandante كبداية: 7–13 كليك للإسبريسو و18–35 للترشيح، وليست وصفة لكل بن. Red Clix يغيّر عدد الخطوات. لا تجبر التروس على الانغلاق ولا تعاير جهازًا بطريقة تخص موديلًا آخر.',
    en: 'Zero and clicks depend on grinder model and burr version. For a standard C40, Comandante suggests starting at 7–13 clicks for espresso and 18–35 for filter, then dialing in. Red Clix changes the step count. Never force burrs shut or apply another model’s calibration procedure.',
    more: ['سجل الموديل وإصدار المحور ونقطة الصفر مع الوصفة؛ هذا يجعل رقم الطحن قابلًا للتكرار داخل نفس الجهاز.', 'Record the model, axle version and zero reference with the recipe so the setting is reproducible on that grinder.'],
    title: 'Comandante — C40 FAQ', url: 'https://comandantegrinder.com/pages/faq',
  },
  {
    id: 'retention', group: 'grinding', titles: ['احتباس البن والتنظيف', 'Retention and grinder care'], priority: 75,
    keywords: /احتباس|بن.*باقي.*طاحون|تنظيف الطاحون|retention|clean.*grinder|grinder care/,
    ar: 'الاحتباس هو البن الذي يبقى داخل الطاحونة؛ يختلف عن تبادل البن القديم بالجديد. زن الداخل والخارج وسجل الفرق، لكن تطابق الوزن لا يثبت عدم وجود تبادل. نظف حسب دليل الموديل؛ لا تغسل التروس أو تنقعها إلا إذا سمح المصنع.',
    en: 'Retention is coffee left inside the grinder, distinct from old grounds exchanging with new grounds. Weigh input and output, but equal weights do not prove zero exchange. Follow model-specific cleaning guidance; wash or soak burrs only when the manufacturer permits it.',
    more: ['إذا تغير الطعم أو تكتل الطحن، ابدأ بتنظيف المخرج والتروس المسموح الوصول لها، ثم أعد الضبط. افصل الكهرباء قبل الصيانة.', 'If taste changes or grounds clump, clean the accessible outlet and burrs as instructed, then dial in again. Disconnect power before servicing.'],
    title: 'Fellow — Ode Gen 2 guide', url: 'https://fellowproducts.com/pages/gear-guide-ode?view=gg-ode-2',
  },
  {
    id: 'fines', group: 'grinding', titles: ['الفاينز وتوزيع الجسيمات', 'Fines and particle distribution'], priority: 85,
    keywords: /فاينز|fines|جسيمات|نخل الطحن|particle distribution|sift/,
    ar: 'الطحن ينتج أحجامًا متعددة؛ الفاينز جسيمات صغيرة قد تزيد الاستخلاص وتؤثر في مقاومة مرور الماء. كثرتها قد تعرقل التدفق، لكن إزالتها كلها ليست حلًا عامًا. النخل يغيّر الجرعة وتوزيع الأحجام، لذلك زن البن بعد النخل إن استخدمته.',
    en: 'Grinding produces many particle sizes. Fines can increase extraction and influence flow resistance; too many can impede flow, but removing all fines is not a universal improvement. Sifting changes both dose and distribution, so weigh the remaining coffee when using it.',
    more: ['قارن بنفس الجرعة بعد النخل والنسبة والماء، ثم سجل التدفق والطعم. لا تستخدم وقت التحضير وحده كدليل على الجودة.', 'Compare at the same post-sifting dose, ratio and water. Record flow and taste; brew time alone is not a quality measurement.'],
    title: 'Barista Hustle — Regrinding experiment', url: 'https://www.baristahustle.com/regrinding/',
  },
  {
    id: 'grinder-rpm', group: 'grinding', titles: ['سرعة دوران الطاحونة', 'Grinder RPM'], priority: 90,
    keywords: /rpm|سرعه دوران|سرعه الطاحون/,
    ar: 'سرعة الدوران قد تغيّر التغذية والحرارة وتوزيع الجسيمات، لكن النتيجة تعتمد على تصميم الطاحونة والبن. لا توجد سرعة واحدة مثالية لكل طاحونة. استخدم نطاق الشركة، وغيّر السرعة وحدها ثم أعد ضبط الطحن عند الحاجة.',
    en: 'RPM can affect feeding, heat and particle distribution, depending on grinder design and coffee. There is no universal best speed. Stay within the manufacturer’s range, change only speed for the comparison and redial grind when needed.',
    more: ['قارن تكرار وزن الناتج والطعم في عدة تحضيرات. توقف عند أصوات احتكاك أو أعطال بدل محاولة علاجها بتغيير السرعة.', 'Compare output weight and taste over repeated brews. Stop for rubbing sounds or faults rather than masking them with a speed change.'],
    title: 'Barista Hustle — Grinder RPM', url: 'https://www.baristahustle.com/coffee-grinder-rpm/',
  },
  {
    id: 'water-treatment', group: 'water', titles: ['الفلترة وRO وإعادة التمعدن', 'Filtration, RO and remineralization'], priority: 80,
    keywords: /فلتر الما[يء]|فلتر مياه|تناضح|معادن الماء|reminerali|reverse osmosis|\bro\b|كلور|chlorine|ماء مقطر/,
    ar: 'فلتر الكربون يساعد في إزالة الكلور لكنه لا يعني خفض العسر. التناضح العكسي RO يقلل أملاحًا كثيرة وقد يحتاج مزجًا أو إعادة تمعدن. ماء التحضير المناسب للطعم قد لا يناسب الماكينة؛ اختبر العسر والقلوية والكلوريد وفق دليلها، ولا تعتمد على TDS وحده.',
    en: 'Carbon filtration can remove chlorine without necessarily reducing hardness. Reverse osmosis reduces many salts and may require blending or remineralization. Good-tasting brew water is not automatically suitable for a machine. Check hardness, alkalinity and chloride against its manual, not TDS alone.',
    more: ['اختبر الماء الداخل للماكينة بعد الفلتر وبدرجة حرارة الاختبار المطلوبة، وأعد القياس بعد تغيير الخرطوشة أو مصدر الماء.', 'Test water after treatment, before it enters the machine, at the required testing temperature. Retest after changing the cartridge or water source.'],
    title: 'La Marzocco — Water calculator', url: 'https://techcenter.lamarzocco.com/en/watercalculator',
  },
  {
    id: 'machine-water', group: 'water', titles: ['الماء والتكلس في الماكينة', 'Machine water and scale'], priority: 85,
    keywords: /تكلس|ترسب|ماء.*ماكين|ماي.*ماكين|espresso water|machine water|scale buildup|chloride|كلوريد/,
    ar: 'التكلس والتآكل يحتاجان فحص تركيب الماء، وليس رقم TDS فقط. مثال خاص بـ La Marzocco من وثيقة الماء: TDS ‏90–150 ppm، العسر الكلي 70–100 ppm، القلوية 40–80 ppm، والكلوريد 0–30 ppm. هذه حدود الشركة في الوثيقة، وليست معيارًا عامًا لكل المكاين؛ راجع دليل موديلك.',
    en: 'Scale and corrosion depend on water composition, not just TDS. A La Marzocco water specification gives TDS 90–150 ppm, total hardness 70–100 ppm, alkalinity 40–80 ppm and chloride 0–30 ppm. These are that manufacturer’s documented limits, not universal machine targets. Check your model’s manual.',
    more: ['لا تخلط قراءة العسر مع القلوية حتى لو كانت الوحدات ppm. أخبرني بموديل الماكينة ونتائج التحليل ووحداتها قبل تقييم الماء.', 'Do not confuse hardness with alkalinity even when both use ppm. Supply the machine model and test values with units before assessing water.'],
    title: 'La Marzocco — Water specification', url: 'https://lamarzoccousa.com/wp-content/uploads/2023/09/Water-Specifications.pdf',
  },
  {
    id: 'boilers', group: 'equipment', titles: ['الغلاية الواحدة والمزدوجة', 'Single and dual boilers'], priority: 65,
    keywords: /غلايه واحده|غلايتين|بويلر|dual boiler|single boiler|boilers/,
    ar: 'الغلاية الواحدة تحتاج عادة الانتقال بين حرارة التحضير والبخار. الغلايتان تفصلان ماء التحضير عن البخار وتساعدان في العمل المتزامن. عدد الغلايات لا يحدد جودة الكوب وحده؛ راجع الثبات الحراري وسرعة الاستعداد والصيانة والمساحة.',
    en: 'A single boiler generally switches between brewing and steaming temperatures. Dual boilers separate brew water and steam and support simultaneous work. Boiler count alone does not determine cup quality; consider temperature stability, readiness, service and space.',
    more: ['حدد كم كوبًا متتاليًا تحضر وكم مشروب حليب. هذا يوضح احتياجك للبخار أكثر من مقارنة أسماء التقنيات وحدها.', 'State how many drinks you make consecutively and how many use milk. This clarifies steam needs better than comparing technology names alone.'],
    title: 'La Marzocco — Dual boilers', url: 'https://nz.lamarzocco.com/news/blog/the-importance-of-dual-boilers/',
  },
  {
    id: 'heat-exchanger', group: 'equipment', titles: ['المبادل الحراري', 'Heat exchanger machines'], priority: 90,
    keywords: /مبادل حراري|heat exchanger|\bhx\b/,
    ar: 'المبادل الحراري يمرر ماء التحضير عبر مسار داخل غلاية ساخنة، ويمكن أن يوفر التحضير والبخار معًا. التحكم والسلوك الحراري يختلفان بين الموديلات؛ لا تفترض أن رقم حرارة الغلاية هو حرارة الماء عند البن، ولا تستخدم تفريغًا حراريًا موحدًا لكل جهاز.',
    en: 'A heat exchanger heats brew water through a path inside a hot boiler and can support brewing and steaming together. Temperature behavior varies by model. Boiler temperature is not necessarily puck temperature, and one cooling-flush routine does not fit every machine.',
    more: ['راجع تعليمات الاستعداد والتفريغ الخاصة بجهازك، وثبّت روتين التسخين قبل مقارنة الوصفات.', 'Follow your machine’s readiness and flushing instructions. Keep warm-up workflow fixed when comparing recipes.'],
    title: 'Profitec — PRO 400 heat exchanger', url: 'https://www.profitec-espresso.com/en/products/pro-400',
  },
  {
    id: 'pid', group: 'equipment', titles: ['PID والثبات الحراري', 'PID and temperature stability'], priority: 95,
    keywords: /\bpid\b|ثبات حراري|تحكم حراري|thermoblock|ثيرموبلوك|temperature stability/,
    ar: 'PID نظام تحكم يضبط التسخين اعتمادًا على قياس الحرارة؛ وجوده لا يعني أن قراءة الشاشة هي حرارة البن الفعلية. الثيرموبلوك يسخّن الماء أثناء مروره، والغلاية تخزن ماء ساخنًا. تصميم مجموعة التحضير وحساسات الجهاز مهم أيضًا.',
    en: 'PID controls heating using temperature feedback; the displayed reading is not necessarily the actual puck temperature. A thermoblock heats passing water, whereas a boiler stores hot water. Group design and sensor placement also matter.',
    more: ['بعد تغيير الإعداد انتظر الاستقرار حسب الدليل. لا تعدّل إزاحة الحساس أو إعدادات الصيانة الداخلية دون إرشادات الشركة.', 'After changing temperature, allow the machine to stabilize as instructed. Do not alter sensor offsets or internal service settings without manufacturer guidance.'],
    title: 'Barista Hustle — PID', url: 'https://www.baristahustle.com/lesson/ae-5-03-the-pid/',
  },
  {
    id: 'pressure', group: 'equipment', titles: ['ضغط الإسبريسو والتدفق', 'Espresso pressure and flow'], priority: 70,
    keywords: /ضغط|بار|pressure|\bbars?\b|flow profil/,
    ar: 'الضغط والتدفق مرتبطان بمقاومة قرص البن. ضغط المضخة المعلن ليس بالضرورة الضغط عند القرص. ليس رفع الضغط حلًا تلقائيًا للحموضة أو السرعة؛ ابدأ بالتوزيع والجرعة والطحن، ثم استخدم وصفة ودليل جهازك.',
    en: 'Pressure and flow interact with puck resistance. Advertised pump pressure is not necessarily pressure at the puck. Increasing pressure is not an automatic fix for sourness or fast shots. Start with distribution, dose and grind, then use the recipe and machine guide.',
    more: ['سجل موضع قياس الضغط ومرحلة القراءة مع وزن الناتج والوقت. لا تفك صمامات الضغط أو تغيّرها اعتمادًا على رقم تسويقي.', 'Record where and when pressure is measured, plus yield and time. Do not adjust internal pressure valves based on a marketing number.'],
    title: 'Barista Hustle — What does 9 bars mean?', url: 'https://www.baristahustle.com/lesson/6-01-what-does-9-bars-mean/',
  },
  {
    id: 'preinfusion', group: 'equipment', titles: ['الترطيب المسبق', 'Preinfusion'], priority: 100,
    keywords: /بري انفيوجن|ترطيب مسبق|preinfusion|pre infusion|pre wetting/,
    ar: 'الترطيب المسبق يبلل قرص الإسبريسو قبل مرحلة الضغط الأساسية. تختلف الآلية بين ضغط الشبكة والتحكم بالمضخة وأجهزة الذراع. سجّل زمن الترطيب وكيف تحسب الوقت الكلي، ولا تنقل ثواني جهاز إلى آخر كأنهما نفس العملية.',
    en: 'Preinfusion wets the espresso puck before the main pressure phase. Line-pressure, pump-controlled and lever machines do this differently. Record preinfusion duration and your shot-time convention rather than copying seconds between unlike systems.',
    more: ['قارن مع تثبيت الجرعة والناتج والتوزيع. إذا تغير التدفق، أعد ضبط الطحن وتذوق بدل الحكم من وقت الشوت وحده.', 'Compare with dose, yield and distribution fixed. If flow changes, redial grind and taste rather than judging shot time alone.'],
    title: 'Barista Hustle — Preinfusion', url: 'https://www.baristahustle.com/lesson/ae-6-07-preinfusion/',
  },
  {
    id: 'puck-prep', group: 'equipment', titles: ['التوزيع والكبس وWDT', 'Distribution, tamping and WDT'], priority: 90,
    keywords: /كبس|تامبر|تمبير|توزيع البن|\bwdt\b|tamp|puck prep|distribut/,
    ar: 'ابدأ بسلة نظيفة وجافة وجرعة مناسبة لها، وفك التكتلات ووزع البن بالتساوي ثم اكبس بشكل مستوٍ ومتكرر. WDT أداة لتوزيع الطحن، وليس بديلًا عن ضبط الجرعة والطاحونة. زيادة قوة الكبس بلا نهاية لا تصلح استخلاصًا غير متجانس.',
    en: 'Use a clean, dry basket and a suitable dose. Break clumps, distribute evenly and tamp level and consistently. WDT helps distribute grounds but does not replace correct dose and grind. Ever-harder tamping does not fix uneven extraction.',
    more: ['كرر نفس الروتين قبل تعديل الطحن. تجنب طرق البورتافلتر بعد الكبس إذا كان يسبب تشققات أو انفصال القرص عن الحافة.', 'Repeat the same preparation before changing grind. Avoid post-tamp knocks that crack the puck or separate it from the basket wall.'],
    title: 'Barista Hustle — Good puck preparation', url: 'https://www.baristahustle.com/lesson/ae-3-01-the-importance-of-good-puck-prep/',
  },
  {
    id: 'channeling', group: 'equipment', titles: ['التشانلنج وعدم تجانس الاستخلاص', 'Channeling and uneven extraction'], priority: 105,
    keywords: /تشانل|تشنل|رش.*اسبر|channel|spray.*espresso|uneven extraction/,
    ar: 'التشانلنج مرور الماء عبر مناطق أسهل داخل قرص البن. الرش والتدفق غير المتجانس إشارات ممكنة، لكن غيابها لا يثبت التجانس. راجع التكتلات والجرعة المناسبة للسلة والكبس المستوي والنظافة قبل تجربة طحن أنعم بكثير.',
    en: 'Channeling means water follows easier paths through the puck. Spraying and uneven flow can be clues, but their absence does not prove even extraction. Check clumps, basket dose, level tamping and cleanliness before making the grind much finer.',
    more: ['صور التدفق تساعد، لكنها لا تقيس الاستخلاص وحدها. قارن الطعم وتكرار الوزن والوقت بعد تغيير خطوة واحدة من تجهيز القرص.', 'Flow images help but do not measure extraction on their own. Compare taste and repeatability after changing one puck-preparation step.'],
    title: 'Barista Hustle — Channeling', url: 'https://www.baristahustle.com/lesson/ae-8-04-what-causes-channelling/',
  },
  {
    id: 'basket-dose', group: 'equipment', titles: ['السلة والبورتافلتر والجرعة', 'Basket, portafilter and dose'], priority: 75,
    keywords: /سله|باسكت|بورتافلتر|headspace|basket|portafilter/,
    ar: 'اختر جرعة تناسب سعة السلة ونوع البن؛ زيادة الجرعة قد تقلل المساحة فوق القرص. مقاس 58 mm لا يضمن توافق كل سلة أو تامبر أو بورتافلتر. السلة المضغوطة وغير المضغوطة تعملان بشكل مختلف، فراجع ملحقات الموديل.',
    en: 'Choose a dose suited to the basket and coffee; overdosing can reduce headspace. A 58 mm label does not guarantee that every basket, tamper or portafilter fits. Pressurized and nonpressurized baskets work differently, so check model compatibility.',
    more: ['إذا كانت الجرعة ثابتة وتحتاج تعديل النكهة، غيّر الناتج أو الطحن أولًا بحسب الوصفة بدل ملء السلة فوق طاقتها.', 'With dose fixed, adjust yield or grind according to the recipe instead of overfilling the basket.'],
    title: 'Barista Hustle — Espresso dose', url: 'https://www.baristahustle.com/espresso-recipes-analyzing-dose/',
  },
  {
    id: 'machine-cleaning', group: 'equipment', titles: ['تنظيف الماكينة والعناية', 'Machine cleaning and maintenance'], priority: 65,
    keywords: /تنظيف|صيان|باك فلاش|backflush|descal|maintenance|clean.*machine/,
    ar: 'نظف السلة والبورتافلتر وأداة التحضير، وامسح عصا البخار بعد الاستعمال وفق الدليل. تنظيف زيوت البن يختلف عن إزالة التكلس. الباك فلاش يحتاج جهازًا يسمح به؛ لا تطبقه على كل ماكينة، ولا تستخدم مزيل تكلس أو منظفًا غير معتمد للموديل.',
    en: 'Clean the basket, portafilter and brewer, and wipe the steam wand after use as instructed. Removing coffee oils differs from descaling. Backflushing is only for compatible machines; use model-approved cleaning agents and procedures.',
    more: ['اتبع تنبيه الجهاز وجدول دليله، وسجل تاريخ تبديل الفلتر والتنظيف. تسريب الماء أو ضعف البخار المستمر يحتاج فحصًا بدل زيادة المنظف.', 'Follow machine reminders and its maintenance schedule. Record filter changes and cleaning. Persistent leaks or weak steam need inspection rather than more detergent.'],
    title: 'Breville — Barista Express cleaning', url: 'https://www.breville.com/en-au/my-products/producthub/bes870/cleaning-guides/how-to-perform-a-cleaning-cycle',
  },
  {
    id: 'scales', group: 'equipment', titles: ['ميزان القهوة ووزن الناتج', 'Scales and brew measurements'], priority: 70,
    keywords: /ميزان|وزن الناتج|coffee scale|weigh|beverage mass/,
    ar: 'زن البن وماء الترشيح أو ناتج الإسبريسو بالغرام، وصفر وزن الوعاء أولًا. تأخر قراءة الميزان قد يسبب تجاوز الناتج، لذلك راقب سلوك ميزانك. المعايرة تحتاج وزنًا مرجعيًا وطريقة الشركة، وحماية الماء تختلف بين الموازين.',
    en: 'Weigh coffee and filter water or espresso yield in grams, and tare the container first. Display lag can cause overshooting, so learn your scale’s response. Calibration needs the manufacturer’s procedure and reference weight; water protection varies by scale.',
    more: ['سجل جرعة البن والناتج منفصلين. لا تستبدل وزن الإسبريسو بملليلترات الكريما؛ الحجم يتغير مع الغاز.', 'Record dose and beverage yield separately. Do not substitute crema volume in milliliters for espresso mass; gas changes the volume.'],
    title: 'Acaia — Lunar manuals', url: 'https://acaia.co/pages/lunar',
  },
  {
    id: 'kettles', group: 'equipment', titles: ['الغلاية والتحكم بالصب', 'Kettles and pouring control'], priority: 65,
    keywords: /غلايه|ابريق الصب|gooseneck|kettle|pouring control/,
    ar: 'الفوهة الرفيعة تساعد على التحكم بمكان ومعدل الصب؛ لا تحدد جودة الماء. حرارة قاعدة الغلاية قد تختلف عن الماء عند البن بسبب النقل وفقد الحرارة. ثبّت كمية الماء والتسخين وارتفاع الصب عند مقارنة الطحن.',
    en: 'A gooseneck helps control pour position and flow; it does not determine water quality. Kettle temperature can differ from water reaching the grounds due to transfer and heat loss. Keep fill, preheating and pour height consistent when comparing grind.',
    more: ['اختر سعة تناسب وصفتك، ولا تتجاوز خط التعبئة. وظيفة حفظ الحرارة مفيدة لتكرار الصبات دون إعادة تسخين عشوائي.', 'Choose capacity for your recipe without exceeding the fill line. Temperature hold can help repeat pours without inconsistent reheating.'],
    title: 'Fellow — Stagg EKG', url: 'https://fellowproducts.com/products/stagg-ekg-electric-pour-over-kettle',
  },
  {
    id: 'filters', group: 'equipment', titles: ['الفلاتر وشكل القطّارة', 'Filters and dripper shape'], priority: 65,
    keywords: /فلتر ورق|فلاتر|قطاره|filter paper|paper filter|dripper|filter shape/,
    ar: 'شكل القطارة والفلتر ومقاسه يغيّر التدفق ومرور الزيوت والجسيمات. استخدم ورقًا يناسب أداتك ورتبه حسب الدليل؛ اختلاف الورق قد يحتاج إعادة ضبط الطحن. شطف الورق والتسخين يتبعان الوصفة والمصنع.',
    en: 'Dripper geometry and filter material and size affect flow and the passage of oils and particles. Use a compatible filter and position it as instructed. Changing paper can require redialing grind. Rinsing and preheating depend on the recipe and manufacturer.',
    more: ['قارن نوعَي ورق بنفس البن والجرعة والصبات. سجل زمن النزول والطعم بدل افتراض أن الأسرع أفضل.', 'Compare two papers with the same coffee, dose and pours. Record drawdown and taste rather than assuming faster is better.'],
    title: 'CAFEC — Filter paper', url: 'https://cafec-jp.com/products/filterpaper/',
  },
  {
    id: 'extraction', group: 'brewing', titles: ['الاستخلاص والطعم', 'Extraction and taste'], priority: 70,
    keywords: /ما هو الاستخلاص|شنو الاستخلاص|نقص الاستخلاص|زياده الاستخلاص|what is extraction|under.?extraction|over.?extraction/,
    ar: 'الاستخلاص ما يأخذه الماء من البن. نقصه قد يعطي كوبًا حادًا أو قليل الحلاوة، وعدم التجانس قد يجمع حموضة ومرارة. هذه إشارات وليست تشخيصًا وحيدًا؛ البن والتحميص والماء يؤثرون أيضًا. غيّر عاملًا واحدًا وسجل الطعم.',
    en: 'Extraction is what water removes from coffee. Too little can taste sharp or lack sweetness; uneven extraction can mix sour and bitter sensations. These are clues rather than a unique diagnosis: coffee, roast and water also matter. Change one variable and record taste.',
    more: ['ابدأ بوصفة موثقة، ثم قارن تعديلًا صغيرًا في الطحن مع تثبيت الجرعة والنسبة. أعطني الطريقة والأوزان والوقت إذا أردت ضبط كوبك.', 'Start from a sourced recipe. Compare a small grind adjustment with dose and ratio fixed. Supply method, weights and time for brew coaching.'],
    title: 'Barista Hustle — Extraction and taste', url: 'https://www.baristahustle.com/coffee-extraction-and-how-to-taste-it/',
  },
  {
    id: 'strength', group: 'brewing', titles: ['التركيز مقابل الاستخلاص', 'Strength versus extraction'], priority: 85,
    keywords: /تركيز.*استخلاص|قوه.*استخلاص|strong.*extract|strength|coffee tds|tds.*قهوه|ناتج الاسبريسو|espresso yield/,
    ar: 'التركيز نسبة المواد الذائبة في المشروب، والاستخلاص نسبة ما أُخرج من البن. زيادة ناتج الإسبريسو تمرر ماء أكثر وقد تزيد الاستخلاص لكنها تخفف التركيز. TDS ماء التحضير ليس TDS القهوة. التخفيف بعد التحضير يقلل التركيز دون إعادة استخلاص البن.',
    en: 'Strength is the dissolved-solids concentration in the beverage; extraction is the fraction removed from the grounds. More espresso yield passes more water and can increase extraction while reducing strength. Brew-water TDS is not beverage TDS. Adding water afterward reduces strength without extracting the grounds again.',
    more: ['للنسبة الحسابية أعطني الجرعة والناتج. قياس نسبة الاستخلاص يحتاج وزن المشروب وقراءة TDS مناسبة للقهوة، ولا يستنتج من وقت الشوت وحده.', 'Give dose and yield for a ratio calculation. Extraction-yield measurement needs beverage mass and a suitable coffee TDS reading; shot time alone cannot determine it.'],
    title: 'Barista Hustle — Understanding yield', url: 'https://www.baristahustle.com/espresso-recipes-understanding-yield/',
  },
  {
    id: 'brewing-temperature', group: 'brewing', titles: ['حرارة ماء التحضير', 'Brewing water temperature'], priority: 60,
    keywords: /حراره.*(?:ماء|ماي|تحضير)|حراره القهوه|brew.*temperature|water temperature|boiling water/,
    ar: 'حرارة الماء تؤثر في سرعة الاستخلاص وتختلف حاجتها حسب البن والطريقة. ابدأ بحرارة الوصفة المنشورة، وثبّت التسخين والصب ثم قارن تعديلًا صغيرًا. حرارة شاشة الجهاز أو الغلاية ليست بالضرورة حرارة الماء في قرص البن.',
    en: 'Water temperature influences extraction speed, with effects depending on coffee and method. Start with the published recipe temperature, keep preheating and pouring fixed and compare a small change. A display reading is not necessarily the temperature at the coffee bed.',
    more: ['لا تعالج المرارة بالحرارة وحدها؛ راجع التحميص والطحن والتجانس. وحرارة التحضير تختلف عن حرارة الشرب المناسبة.', 'Do not treat bitterness through temperature alone; check roast, grind and evenness. Brewing temperature and drinking temperature are different.'],
    title: 'NCA — Pour-over brewing', url: 'https://www.aboutcoffee.org/brewing/pour-over-coffee/',
  },
  {
    id: 'milk', group: 'brewing', titles: ['الحليب والتبخير', 'Milk and steaming'], priority: 80,
    keywords: /حليب|تبخير|لاتيه|كابتشينو|milk|steam wand|latte|cappuccino/,
    ar: 'التبخير يجمع إدخال الهواء وتسخين الحليب وصنع دوامة لتوزيع الفقاعات. ابدأ بحليب بارد وكمية مناسبة للإبريق، ونظف عصا البخار حسب دليل الجهاز. الحليب النباتي يختلف في البروتين والتركيب؛ النسخ المخصصة للباريستا قد تعطي رغوة أكثر استقرارًا.',
    en: 'Steaming combines aeration, heating and circulation to distribute bubbles. Start with cold milk and a suitable pitcher fill, and clean the wand as instructed. Plant milks differ in protein and composition; barista formulations may foam more consistently.',
    more: ['الرغوة الكبيرة قد تعني إدخال هواء زائد أو ضعف الدوامة. غيّر موضع العصا قليلًا داخل حدود الدليل، ولا تعاود تبخير الحليب مرارًا.', 'Large bubbles can indicate excess air or poor circulation. Adjust wand position within the manual’s guidance, and avoid repeatedly resteaming milk.'],
    title: 'Breville — Microfoam milk', url: 'https://www.breville.com/au/en/coffee-journey/tutorials/espresso-tutorials/microfoam-milk.html',
  },
  {
    id: 'roast-stages', group: 'roasting', titles: ['مراحل التحميص من الأخضر إلى البني', 'Roast stages: green to brown'], priority: 35,
    keywords: /مراحل.*(?:حمص|تحميص)|شلون.*(?:احمص|حمص)|طريقه الحمص|تحميص|حمص|roast stages|how.*roast|roasting/,
    ar: 'البن الأخضر مادة البداية وليس درجة تحميص. أثناء التسخين يصفرّ ثم يتحول إلى البني، وتتطور الروائح. الفرقعة الأولى حدث مسموع، يليها التطوير حتى إنزال البن والتبريد. سجل اللون والرائحة والصوت والمنحنى معًا؛ لا يوجد وقت أو حرارة نهاية واحدة لكل المكاين.',
    en: 'Green coffee is the raw starting material, not a roast level. Heating changes it toward yellow and then brown as aromas develop. First crack is an audible event, followed by development until drop and cooling. Record color, aroma, sound and the curve together; one endpoint time or temperature cannot fit every roaster.',
    more: ['للوصول لبني فاتح، استخدم حمصة مرجعية لمحمصتك وأنزل عند هدف لون وطعم مطور. للمتوسط أو الغامق عدّل نقطة النهاية تدريجيًا مع تبريد ثابت وتذوق مقارن.', 'For light brown, use a reference profile for your machine and a developed color-and-taste target. For medium or dark, adjust the endpoint gradually with consistent cooling and comparative tasting.'],
    title: 'Mill City Roasters — Sensory cues', url: 'https://millcityroasters.com/blogs/coffee-articles/roastery-sensory-cues',
  },
  {
    id: 'maillard', group: 'roasting', titles: ['الاصفرار وتفاعل ميلارد', 'Yellowing and Maillard reactions'], priority: 90,
    keywords: /ميلارد|اصفرار|maillard|yellowing|browning/,
    ar: 'التحول من الأخضر إلى الأصفر ثم البني يساعد على متابعة الحمصة. تفاعلات ميلارد بين مركبات السكر والأحماض الأمينية تسهم في الروائح واللون البني. تقسيم الحمصة لمراحل أداة للتسجيل؛ التفاعلات تتداخل وليست مفاتيح تُفتح عند درجة ثابتة.',
    en: 'The shift from green toward yellow and brown helps track roasting. Maillard reactions involving sugars and amino compounds contribute aroma and browning. Roast phases are a recording framework; reactions overlap rather than switching on at a universal temperature.',
    more: ['سجل لحظة الاصفرار بمعيار واحد لكل دفعاتك، وقارن الرائحة واللون في نفس الإضاءة. لا تنقل العلامة الحرارية بين حساسَي محمصتين مختلفتين.', 'Use one yellowing criterion across your batches. Compare aroma and color under consistent light, without transferring sensor landmarks between different roasters.'],
    title: 'SCA — Roast color and flavor', url: 'https://sca.coffee/sca-news/coffee-decoded-4-roast-color',
  },
  {
    id: 'rate-of-rise', group: 'roasting', titles: ['RoR ومنحنى التحميص', 'RoR and the roast curve'], priority: 95,
    keywords: /\bror\b|rate of rise|معدل الارتفاع|منحنى التحميص|كراش|فلك|crash|flick/,
    ar: 'RoR معدل تغير قراءة الحرارة لكل دقيقة، وليس درجة التحميص. يتأثر بنوع الحساس والتنعيم وحجم الدفعة. الارتفاع أو الانخفاض المفاجئ يحتاج مراجعة الطاقة والهواء والقراءات، ولا يثبت عيبًا في الطعم وحده. قارن بيانات من نفس الحساس والجهاز.',
    en: 'RoR is the rate of temperature change per minute, not roast degree. Sensor type, smoothing and batch size affect it. Sudden changes warrant reviewing energy, airflow and readings, but alone do not prove a flavor defect. Compare data from the same sensor and roaster.',
    more: ['ثبّت إعداد تسجيل المنحنى وتنعيمه، وسجل تغييرات الطاقة والهواء مع الوقت. اربط النتيجة بتذوق البن بعد الراحة بدل مطاردة شكل منحنى مثالي.', 'Keep logging and smoothing settings consistent. Record timed energy and airflow changes, then relate the result to tasting after rest rather than pursuing an ideal-looking curve.'],
    title: 'Aillio — R2 roasting controls', url: 'https://docs.aillio.com/bullet-r2/operation/roasting-with-r2/',
  },
  {
    id: 'roast-control', group: 'roasting', titles: ['الطاقة والهواء وحجم الدفعة', 'Heat, airflow and batch size'], priority: 80,
    keywords: /طاقة التحميص|هواء التحميص|دفعه التحميص|حجم الدفعه|preheat|charge temp|airflow|roast power|batch size/,
    ar: 'التسخين المسبق والطاقة والهواء ووزن الدفعة تعمل معًا. الدرم يحتفظ بطاقة مختلفة عن محمصة الهواء، وحساس الهواء ليس حساس البن. ابدأ بنطاق الدفعة وإعدادات دليل الموديل، ثم غيّر عاملًا واحدًا وسجل أثره.',
    en: 'Preheat, power, airflow and batch mass interact. A drum retains energy differently from an air roaster, and air-temperature and bean-temperature sensors are not interchangeable. Start within the model’s batch range and documented settings, then change one variable and record its effect.',
    more: ['تحويل منحنى بين محمصتين يحتاج معرفة نوع الحساس والدفعة والتدفق. استخدمه كمرجع أحداث وطعم، لا كجدول درجات منسوخ.', 'Transferring a curve requires sensor, batch and airflow information. Use it as an event-and-flavor reference rather than a copied temperature schedule.'],
    title: 'IKAWA — Controlling roast variables', url: 'https://www.ikawacoffee.com/wp-content/uploads/2021/04/How-to-roast-with-IKAWA.pdf',
  },
  {
    id: 'roast-color', group: 'roasting', titles: ['قياس لون التحميص وAgtron', 'Measuring roast color and Agtron'], priority: 100,
    keywords: /agtron|اجترون|قياس اللون|لون البن|بني فاتح|بني غامق|roast colou?r|light brown|dark brown/,
    ar: 'صور الأخضر والبني الفاتح والمتوسط والغامق مرجع بصري فقط؛ الإضاءة والشاشة تؤثر فيه. أجهزة اللون مثل Agtron تقيس بعينة وطريقة معايرة محددة. سجل قياس الحبة الكاملة والمطحونة منفصلين، ولا تحوّل صورة جوال إلى قراءة مخبرية.',
    en: 'Pictures of green, light, medium and dark beans are visual references; lighting and screens alter appearance. Instruments such as Agtron require a specified sample and calibration procedure. Record whole-bean and ground measurements separately; a phone photo is not a laboratory reading.',
    more: ['اتبع دليل جهاز اللون في تحضير العينة والمعايرة، وثبّت الطحن ووقت القياس. رقم أو اسم اللون لا يقيس التطوير الداخلي أو جودة الطعم وحده.', 'Follow the color instrument’s preparation and calibration instructions, keeping grind and measurement timing consistent. Color names or numbers alone do not measure internal development or cup quality.'],
    title: 'UC Davis research — Universal roast color curve', url: 'https://www.nature.com/articles/s41598-025-06601-w',
  },
  {
    id: 'roast-defects', group: 'roasting', titles: ['عيوب التحميص وتشخيصها', 'Roast defects and diagnosis'], priority: 100,
    keywords: /عيوب التحميص|محروق|تلسيع|سكورش|تيبنج|scorch|tipping|baked roast|underdeveloped|نقص التطوير/,
    ar: 'بقع سوداء موضعية قد تشير إلى تلسيع، وأطراف متفحمة قد تشير إلى tipping. الطعم العشبي أو الجاف يحتاج فحص التطوير والتحضير معًا. لا تشخّص baked من طول الحمصة وحده. افحص العينة والمنحنى والماء ووصفة التذوق قبل تعديل الحرارة.',
    en: 'Localized dark spots can indicate scorching, while charred tips can indicate tipping. Grassy or drying cups need both roast and brewing checks. Roast duration alone cannot diagnose baking. Inspect the sample, curve, water and tasting recipe before changing heat.',
    more: ['قارن دفعة مرجعية بنفس البن والماء، وافحص حبات كاملة ومطحونة. عدّل الطاقة أو نقطة النهاية مرة واحدة ثم أعد التذوق.', 'Compare a reference batch with the same coffee and water, inspecting whole and ground beans. Change energy or endpoint once, then taste again.'],
    title: 'Mill City Roasters — Heat defects', url: 'https://millcityroasters.com/blogs/coffee-articles/roastery-sensory-cues',
  },
  {
    id: 'roast-cooling', group: 'roasting', titles: ['التبريد والقشور والعناية بالمحمصة', 'Cooling, chaff and roaster care'], priority: 95,
    keywords: /تبريد.*(?:بن|حمص)|قشور|chaff|cooling.*(?:bean|roast)|roaster maintenance|تنظيف المحمص/,
    ar: 'بعد الإنزال، التبريد يحد من استمرار أثر الحرارة. نظف مجمع القشور ومسار الهواء حسب دليل المحمصة. لا توقف مراوح التبريد أو تفصل الجهاز الساخن بطريقة تخالف الدليل؛ بقايا القشور والدخان تؤثر في التشغيل وتزيد مخاطر الحريق.',
    en: 'Cooling after drop limits continuing heat effects. Clean the chaff collector and airflow path as instructed. Do not stop cooling fans or disconnect a hot roaster contrary to its manual. Chaff and smoke residue affect operation and increase fire risk.',
    more: ['سجل مدة التبريد ودرجة النهاية إن كانت مقاسة. ثبت طريقة التبريد قبل مقارنة نقطتي إنزال، واتبع إجراءات الشركة لأي دخان غير طبيعي.', 'Record cooling duration and final temperature when measured. Keep cooling consistent while comparing drop endpoints, and follow manufacturer procedures for abnormal smoke.'],
    title: 'Aillio — R2 maintenance', url: 'https://docs.aillio.com/bullet-r2/operation/maintaining-the-r2/',
  },
  {
    id: 'development-time', group: 'roasting', titles: ['الفرقعة ووقت التطوير وDTR', 'First crack, development and DTR'], priority: 100,
    keywords: /فرقعه|تطوير.*حمص|وقت التطوير|\bdtr\b|first crack|second crack|development time/,
    ar: 'وقت التطوير في تسجيل الحمصة هو الفترة من بداية الفرقعة الأولى المسجلة إلى الإنزال. DTR = وقت التطوير ÷ الوقت الكلي × 100. نفس النسبة لا تعني نفس اللون أو الطعم، ولا توجد نسبة سحرية لكل بن. سجل معيار سماع الفرقعة ومكان حساس الحرارة.',
    en: 'Recorded development time runs from the marked start of first crack to drop. DTR = development time ÷ total time × 100. Equal ratios do not imply equal color or flavor, and no universal magic ratio exists. Record your crack criterion and temperature-sensor location.',
    more: ['مثال حسابي: فرقعة عند 8:00 وإنزال عند 10:00 تعطي تطوير دقيقتين وDTR ‏20%. المثال يشرح الحساب ولا يوصي بهذه النهاية.', 'Arithmetic example: first crack at 8:00 and drop at 10:00 gives two minutes of development and 20% DTR. This explains calculation without recommending that endpoint.'],
    title: 'Münchow & Alstrup — Time and color study', url: 'https://www.roastmagazine.com/stories/flavor-development-the-relationship-between-time-and-color-in-coffee-roasting',
  },
  {
    id: 'flavor-notes', group: 'sensory', titles: ['الإيحاءات والرائحة والقوام', 'Flavor notes, aroma and texture'], priority: 75,
    keywords: /ايحاء|نكه|flavo[u]?r notes|aroma|mouthfeel|texture|رائحه|قوام/,
    ar: 'الإيحاءات وصف لما يذكّرنا به الكوب، وليست دليلًا على إضافة فاكهة أو شوكولاتة. افصل الرائحة والطعم والحموضة والمرارة والقوام والأثر اللاحق. معجم World Coffee Research يقدم أوصافًا ومراجع حسية؛ وصف النكهة يختلف عن تقييم تفضيلك الشخصي.',
    en: 'Flavor notes describe what a cup reminds us of; they do not establish that fruit or chocolate was added. Separate aroma, flavor, acidity, bitterness, texture and aftertaste. World Coffee Research provides sensory descriptors and references; describing flavor differs from rating your preference.',
    more: ['ابدأ بفئة عامة مثل فاكهي أو مكسرات، ثم وصف أدق إذا تكرر إحساسك. تذوق الكوب وهو يبرد ودوّن الشدة بدل مطاردة كلمة العبوة.', 'Start with a broad family such as fruit or nuts, then narrow it if the sensation repeats. Taste as the cup cools and record intensity rather than chasing the bag label.'],
    title: 'World Coffee Research — Sensory lexicon', url: 'https://worldcoffeeresearch.org/resources/sensory-lexicon',
  },
  {
    id: 'cupping', group: 'sensory', titles: ['التذوق المقارن والكَبِنغ', 'Comparative tasting and cupping'], priority: 90,
    keywords: /كبنغ|كابينج|تذوق مقارن|cupping|blind tast|sensory evaluation/,
    ar: 'التذوق المقارن يحتاج نفس الماء والجرعة والطحن والحرارة والزمن. رمّز العينات لتقليل تأثير الاسم، وقارنها في أكثر من درجة حرارة. افصل وصف ما تذوقته عن إعجابك به؛ نظام CVA لدى SCA يميز التقييم الوصفي عن الانطباع عن الجودة.',
    en: 'Comparative tasting requires consistent water, dose, grind, temperature and time. Code samples to reduce label bias and compare at several temperatures. Separate observed descriptors from liking; the SCA’s CVA separates descriptive assessment from quality impressions.',
    more: ['كرر المقارنة ولا تعتبر كوبًا واحدًا نتيجة علمية قاطعة. سجل الاختلافات والظروف، وارجع للبروتوكول الرسمي إن أردت تقييمًا مهنيًا.', 'Repeat the comparison rather than treating one cup as conclusive research. Record differences and conditions; use the official protocol for professional assessment.'],
    title: 'SCA — CVA standards', url: 'https://sca.coffee/sca-news/sca-new-cva-cupping-standards-7ga28',
  },
];
