/** Bilingual tasting-note labels and retrieval aliases. They do not assert a note for any coffee. */
export const flavorTranslations: Record<string, string> = {
  allspice: "بهار حلو",
  amaretto: "أماريتو",
  "barley tea": "شاي الشعير",
  biscuits: "بسكويت",
  blackberries: "توت أسود",
  "butter biscuit": "بسكويت بالزبدة",
  butterscotch: "كراميل بالزبدة",
  "candied almond": "لوز محلّى",
  "candied lemon": "ليمون محلّى",
  "cane sugar": "سكر القصب",
  "cashew butter": "زبدة الكاجو",
  "cherry filled doughnut": "دونات بحشوة الكرز",
  "chocolate fudge": "فدج الشوكولاتة",
  "chocolate milk": "حليب بالشوكولاتة",
  clean: "واضحة",
  clementine: "كلمنتينا",
  cola: "كولا",
  cookies: "بسكويت",
  "creamy white chocolate": "شوكولاتة بيضاء كريمية",
  currants: "كشمش",
  currant: "كشمش",
  "dark grape": "عنب داكن",
  "dried berries": "توت مجفف",
  "earl grey": "شاي إيرل غراي",
  fig: "تين",
  florals: "زهور",
  fruits: "فواكه",
  "grape soda": "مشروب عنب غازي",
  "heavy chocolate": "شوكولاتة كثيفة",
  honeycomb: "قرص العسل",
  honeydew: "شمام عسلي",
  honeysuckle: "زهرة العسلة",
  "juicy & citrus finish": "قوام عصيري ونهاية حمضية",
  "key lime": "لايم",
  kumquat: "كمكوات",
  lime: "لايم",
  "lime curd": "كريمة اللايم",
  "lotus biscuit": "بسكويت لوتس",
  malt: "شعير",
  mandarin: "يوسفي",
  maple: "قيقب",
  "maple syrup": "شراب القيقب",
  matcha: "ماتشا",
  melon: "شمام",
  "mulled wine": "نبيذ متبّل",
  "mulling spice": "توابل دافئة",
  "myrtle liquor": "مشروب الآس",
  panela: "سكر قصب غير مكرر",
  "peanut butter": "زبدة الفول السوداني",
  pecan: "بيكان",
  "pink grapefruit": "جريب فروت وردي",
  "raspberry candy": "حلوى توت العليق",
  "raw honey": "عسل خام",
  "red grape": "عنب أحمر",
  "red wine": "نبيذ أحمر",
  redcurrant: "كشمش أحمر",
  "red currant": "كشمش أحمر",
  "red currants": "كشمش أحمر",
  redcurrants: "كشمش أحمر",
  refined: "رقيقة",
  rhubarb: "راوند",
  "ripe fruits": "فواكه ناضجة",
  "ripe orange": "برتقال ناضج",
  "roasted almonds": "لوز محمص",
  "roasted macadamia": "مكاديميا محمصة",
  round: "متوازنة",
  silky: "حريرية",
  spearmint: "نعناع",
  spices: "توابل",
  "stone fruits": "فواكه ذات نواة",
  sugarcane: "قصب السكر",
  "sweet berries": "توت حلو",
  "sweet blood orange": "برتقال أحمر حلو",
  "sweet tea": "شاي حلو",
  "tart apple": "تفاح حامض",
  "thick & syrupy": "قوام كثيف",
  "tropical fruits": "فواكه استوائية",
  "tropical fruit": "فاكهة استوائية",
  "vanilla cake": "كيك الفانيلا",
  "vanilla malt": "شعير بالفانيلا",
  violet: "بنفسج",
  waffle: "وافل",
  "white florals": "زهور بيضاء",
  "white grape": "عنب أبيض",
  "white wine": "نبيذ أبيض",
  "white chocolate": "شوكولاتة بيضاء",
  "white peach": "خوخ أبيض",
  "passion fruit": "باشن فروت",
  passionfruit: "باشن فروت",
  "burnt sugar": "سكر محروق",
  "dried cherry": "كرز مجفف",
  "dried apricot": "مشمش مجفف",
  "orange marmalade": "مربى البرتقال",
  "black cherry": "كرز أسود",
  "red grapes": "عنب أحمر",
  nutmeg: "جوزة الطيب",
  marzipan: "مرزبان",
  sultana: "زبيب سلطاني",
  "bitter orange": "برتقال مر",
  pear: "إجاص",
  "miso caramel": "كراميل الميسو",
  stonefruit: "فواكه ذات نواة",
  "star anise": "يانسون نجمي",
  kiwi: "كيوي",
  "berries jam": "مربى توت",
  "grape yoghurt": "زبادي العنب",
  winegum: "حلوى فاكهة",
  "peach iced tea": "شاي خوخ مثلج",
  "jammy berries": "توت بقوام مربى",
  "sweet candy": "حلوى",
  "winey fruitiness": "فاكهة مخمّرة",
  "candy-like finish": "نهاية حلوة",
  "slight floral": "لمسة زهرية",
  chocolate: "شوكولاتة",
  "milk chocolate": "شوكولاتة بالحليب",
  "dark chocolate": "شوكولاتة داكنة",
  cocoa: "كاكاو",
  cacao: "كاكاو",
  nutty: "مكسرات",
  nuts: "مكسرات",
  almond: "لوز",
  almonds: "لوز",
  hazelnut: "بندق",
  hazelnuts: "بندق",
  pistachio: "فستق",
  walnut: "جوز",
  fruity: "فواكه",
  fruit: "فواكه",
  citrus: "حمضيات",
  lemon: "ليمون",
  orange: "برتقال",
  grapefruit: "جريب فروت",
  bergamot: "برغموت",
  floral: "زهور",
  jasmine: "ياسمين",
  rose: "ورد",
  hibiscus: "كركديه",
  peach: "خوخ",
  apricot: "مشمش",
  mango: "مانجو",
  "stone fruit": "فواكه ذات نواة",
  honey: "عسل",
  caramel: "كراميل",
  toffee: "توفي",
  "brown sugar": "سكر بني",
  spice: "توابل",
  cinnamon: "قرفة",
  cardamom: "هيل",
  berry: "توت",
  berries: "توت",
  raspberry: "توت العليق",
  strawberry: "فراولة",
  blueberry: "توت أزرق",
  blackberry: "توت أسود",
  cherry: "كرز",
  apple: "تفاح",
  "red apple": "تفاح أحمر",
  "green apple": "تفاح أخضر",
  plum: "برقوق",
  grape: "عنب",
  grapes: "عنب",
  raisin: "زبيب",
  raisins: "زبيب",
  vanilla: "فانيلا",
  lavender: "لافندر",
  chamomile: "بابونج",
  "black tea": "شاي أسود",
  "yellow plum": "برقوق أصفر",
  dates: "تمر",
  cloves: "قرنفل",
  lychee: "ليتشي",
  cantaloupe: "شمام",
  pineapple: "أناناس",
  mandarine: "يوسفي",
  tangerine: "يوسفي",
  pomegranate: "رمان",
  "dried fig": "تين مجفف",
  "red berries": "توت أحمر",
  "red berry": "توت أحمر",
  "mixed berries": "توت مشكّل",
  "black berries": "توت داكن",
  "almond cream": "كريمة اللوز",
  "blood orange": "برتقال أحمر",
  nectarine: "نكتارين",
  lemongrass: "عشبة الليمون",
  "dried fruit": "فواكه مجففة",
  "dried fruits": "فواكه مجففة",
  blackcurrant: "كشمش أسود",
  "black currant": "كشمش أسود",
  "black currants": "كشمش أسود",
  blackcurrants: "كشمش أسود",
  "white grapes": "عنب أبيض",
  "blueberry pie": "فطيرة التوت الأزرق",
  "candied pecan": "بيكان مُحلّى",
  "roasted walnuts": "جوز محمّص",
  "cacao nibs": "قطع الكاكاو",
  "candied walnuts": "جوز مُحلّى",
  liquorice: "عرق السوس",
  molasses: "دبس",
  "maraschino cherries": "كرز ماراشينو",
  "fruit-smoked": "فواكه مع لمسة دخان",
  nougat: "نوجا",
  praline: "برالين",
  maltesers: "مالتيزرز",
  sweet: "حلوة",
  elegant: "أنيقة",
  botanical: "نباتية",
  "sweet citrus": "حمضيات حلوة",
  "orange zest": "قشر البرتقال",
  "sugar cane": "قصب السكر",
  beeswax: "شمع العسل",
  "yellow peach": "خوخ أصفر",
};
export const flavorSearchVocabulary = Object.entries(flavorTranslations);
