import { setLanguage } from './settings';
import { selectProfileExtra } from './profile-navigation';
import {test,expect,type Route,type Page} from '@playwright/test';
const uid='11111111-1111-4111-8111-111111111111';
const user={id:uid,aud:'authenticated',role:'authenticated',email:'social@example.test',is_anonymous:false,app_metadata:{provider:'email',providers:['email']},user_metadata:{},identities:[],created_at:'2026-01-01T00:00:00Z'};
const enc=(v:object)=>Buffer.from(JSON.stringify(v)).toString('base64url');
const token=`${enc({alg:'HS256',typ:'JWT'})}.${enc({sub:uid,role:'authenticated',is_anonymous:false,exp:Math.floor(Date.now()/1000)+3600})}.isolated_signature`;
const other={id:'22222222-2222-4222-8222-222222222222',name:'Private Barista',username:'barista',avatar_url:null,is_private:true};
async function reply(route:Route,data:unknown,status=200){return route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});}
async function signIn(page:Page){await page.goto('/');await setLanguage(page, 'en');await page.getByRole('button',{name:'Account',exact:true}).click();await page.getByLabel('Email',{exact:true}).fill(user.email);await page.getByLabel('Password',{exact:true}).fill('isolated-fixture-password');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByTestId("account-screen")).toBeVisible();}
function auth(path:string){return path.endsWith('/token')?{access_token:token,token_type:'bearer',expires_in:3600,refresh_token:'isolated_refresh',user}:path.endsWith('/user')?user:null;}
test('search by username shows private identity; request stays pending and collections remain hidden',async({page})=>{
 let relationship:null|'pending'=null;let followed=0;const queries:string[]=[];
 await page.route('https://mobilefixture.supabase.co/**',async route=>{const url=new URL(route.request().url()),p=url.pathname,a=auth(p);if(a)return reply(route,a);if(p.endsWith('/profiles'))return reply(route,{username:'owner'});
 if(p.endsWith('/rpc/search_member_profiles')){queries.push(route.request().postDataJSON().p_query);return reply(route,[other]);}
 if(p.endsWith('/rpc/get_member_profile')){const own=route.request().postDataJSON().p_username==='owner';return reply(route,{profile:own?{id:uid,name:'Owner',username:'owner',bio:'',is_private:false,share_collection:false}:other,is_owner:own,can_view:own,relationship,follower_count:0,following_count:0});}
 if(p.endsWith('/follows')&&route.request().method()==='POST'){expect(route.request().postDataJSON()).toEqual({follower_id:uid,following_id:other.id});followed++;relationship='pending';return reply(route,{status:'pending'});}return reply(route,[]);});
 await page.setViewportSize({width:320,height:900});await signIn(page);await page.getByRole('button',{name:'coffeeHO',exact:true}).click();await page.getByRole('button',{name:'coffeeHO accounts',exact:true}).click();await page.getByLabel('Search by name or username',{exact:true}).fill('@barista');await expect.poll(()=>queries.at(-1)).toBe('barista');await page.getByRole('button',{name:'Private Barista @barista',exact:true}).click();
 await expect(page.getByText('This account is private. Request to follow to view details after approval.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Follow',exact:true}).click();await expect(page.getByRole('button',{name:'Cancel follow request',exact:true})).toBeVisible();expect(followed).toBe(1);await expect(page.getByRole('button',{name:'Manage my equipment',exact:true})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('own profile exposes username and collections, validates privacy update, approves a request and saves a corner photo',async({page})=>{
 const profile={id:uid,name:'Coffee Owner',username:'owner',bio:'My coffee',avatar_url:null,is_private:false,share_collection:false};let pending=true;const changes:unknown[]=[];const uploads:string[]=[];let photoSaved=false;
 await page.route('https://mobilefixture.supabase.co/**',async route=>{const url=new URL(route.request().url()),p=url.pathname,a=auth(p);if(a)return reply(route,a);
 if(p.endsWith('/profiles')){if(route.request().method()==='PATCH'){const body=route.request().postDataJSON();changes.push(body);expect(url.searchParams.get('id')).toBe('eq.'+uid);Object.assign(profile,body);return reply(route,{id:uid});}return reply(route,{username:'owner'});}
 if(p.endsWith('/rpc/get_member_profile'))return reply(route,{profile,is_owner:true,can_view:true,relationship:null,follower_count:pending?0:1,following_count:0,equipment:[{id:'gear',name:'Hand grinder',name_ar:'طاحونة يدوية',category:'grinder',equipment_model_id:null,operation:['يدوية','Manual']}],beans:[{id:'bag',coffee_id:'coffee',kind:'bean',name_ar:'بن التجربة',name_en:'Test coffee',slug:'test'}],recipes:[{id:'recipe',title:'My recipe',title_ar:'وصفتي',brew_method:'v60',visibility:'private'}],favorites:[{id:'favorite',title:'Favorite recipe',title_ar:'وصفة مفضلة',brew_method:'v60'}],comments:[{id:'comment',body:'Great coffee extraction',kind:'recipe',target_id:'recipe',name_en:'My recipe',name_ar:'وصفتي'}],photos:[],requests:pending?[{...other,request_id:'request'}]:[]});
 if(p.endsWith('/follows')&&route.request().method()==='PATCH'){expect(url.searchParams.get('following_id')).toBe('eq.'+uid);pending=false;return reply(route,{id:'request'});}
 if(p.startsWith('/storage/v1/object/profile-gallery/')){uploads.push(p);return reply(route,{Key:p});}
 if(p.endsWith('/rpc/save_profile_photo')){const b=route.request().postDataJSON();expect(b.p_kind).toBe('corner');expect(b.p_caption).toBe('My espresso corner');expect(b.p_path).toBe(`${uid}/${b.p_id}.png`);photoSaved=true;return reply(route,b.p_id);}return reply(route,[]);});
 await signIn(page);await expect(page.getByText('@owner',{exact:true})).toBeVisible();await expect(page.getByText('Hand grinder',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Edit profile',exact:true}).click();await page.getByRole('button',{name:'Private',exact:true}).click();await page.getByRole('checkbox',{name:'Share equipment, coffee and favorites',exact:true}).click();await page.getByRole('button',{name:'Save profile',exact:true}).click();await expect.poll(()=>changes.length).toBe(1);expect(changes[0]).toMatchObject({is_private:true,share_collection:true});
 await page.getByRole('button',{name:'Accept',exact:true}).click();await expect(page.getByRole('button',{name:'Accept',exact:true})).toHaveCount(0);
 await selectProfileExtra(page, 'Favorite recipes');await expect(page.getByRole('button',{name:'Favorite recipe',exact:true})).toBeVisible();await selectProfileExtra(page, 'Comments');await expect(page.getByText('Great coffee extraction',{exact:true})).toBeVisible();
 await selectProfileExtra(page, 'Brews & coffee corner');await page.getByRole('button',{name:'Coffee corner',exact:true}).click();await page.getByLabel('Photo caption',{exact:true}).fill('My espresso corner');const choose=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Choose photo',exact:true}).click();await(await choose).setFiles({name:'corner.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')});await page.getByRole('checkbox').click();await page.getByRole('button',{name:'Save photo',exact:true}).click();await expect.poll(()=>photoSaved).toBe(true);expect(uploads).toHaveLength(1);
});
